<form id="frmReporte-kardex" name="frmReporte-kardex" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
  <input type="hidden" name="txtpar3" id="txtpar3" />
  <input type="hidden" name="txtpar4" id="txtpar4" />
  <input type="hidden" name="txtpar5" id="txtpar5" />
  <input type="hidden" name="txtpar6" id="txtpar6" />
  <input type="hidden" name="txtpar7" id="txtpar7" />
</form>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    Ext.ns('kardex');
    kardex={
        id:'kardex',
        init:function(){
            /*Ext.Ajax.timeout = 180000;*/
            Ext.QuickTips.init();
			
			//Panel 1 >>>
			
			var txt_anio = new Ext.form.NumberField({   
				id:kardex.id+'-txt_anio' , 
                value:'2012',
				width:80,
				maxValue:2030,
				minValue:1990,
				decimalPrecision :0,
				listeners:{
					specialkey:function(obj, e)
					{
						if (e.getKey() == 13)
						{
							if(obj.getValue()<0){
								return;
							}
							if(Ext.getCmp(kardex.id+'-combo_monedas').getValue()==''){
								return;
							}
							if(Ext.getCmp(kardex.id+'-mcd_id').getValue()=='0'){
								return;
							}
							Ext.getCmp(kardex.id+'-grid_lista').store.removeAll();
								Ext.getCmp(kardex.id+'-grid_lista').store.load({params:{anio:obj.getValue(), mon_id:Ext.getCmp(kardex.id+'-combo_monedas').getValue(),pro_id:Ext.getCmp(kardex.id+'-mcd_id').getValue(),start:0,limit:100}});
						}
					}
				}
			});
			
			var txt_producto = new Ext.form.TextField({   
				id:kardex.id+'-txt_producto' , 
                value:'',
				width:350,
				readOnly:true
			});
			
			var btn_producto=new Ext.Button({
                id:kardex.id+'-btn_producto',
                text:'Producto...',
                icon:'images/icon/ver.png',
                listeners:
                    {
                        click:function()
                        {
							kardex.fn_producto();                            
                        }
                    }
            });
			
			var btn_imprimir=new Ext.Button({
                id:kardex.id+'-btn_imprimir',
                text:'Imprimir',
                icon:'images/icon/printer.png',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea imprimir listado?', function(btn) {
                                if(btn == 'yes')
                                {
                                    kardex.fn_imprimir();
                                }
                            });

                            
                        }
                    }
            });
			
			var store_monedas_lista=new Ext.data.JsonStore({
                url:'tablas/monedas-lista',
                root:'data',
                totalProperty:'total',
                fields:['mon_id','nombre']
            });
            
            store_monedas_lista.load();
			
			var combo_monedas=new Ext.form.ComboBox({
                id:kardex.id+'-combo_monedas',
                store:store_monedas_lista,
                valueField:'mon_id',
                displayField:'nombre',
                triggerAction:'all',
                emptyText:'Moneda...',
                mode:'local',
                width:100,
                editable:false,
				listeners:{
					select:function(obj){
						//alert(obj.getValue());
						if(Ext.getCmp(kardex.id+'-txt_anio').getValue()<0){
							return;
						}
						if(obj.getValue()==''){
							return;
						}
						if(Ext.getCmp(kardex.id+'-mcd_id').getValue()=='0'){
							return;
						}
						//alert(Ext.getCmp(kardex.id+'-txt_anio').getValue() +  '-'+Ext.getCmp(kardex.id+'-mcd_id').getValue());
						Ext.getCmp(kardex.id+'-grid_lista').store.removeAll();
							Ext.getCmp(kardex.id+'-grid_lista').store.load({params:{anio:Ext.getCmp(kardex.id+'-txt_anio').getValue(), mon_id:obj.getValue(),pro_id:Ext.getCmp(kardex.id+'-mcd_id').getValue(),start:0,limit:100}});
					}
				}
            });
            
			
			var store_kardex_lista=new Ext.data.JsonStore({
                url:'maestros/kardex-lista',
                root:'data',
                totalProperty:'total',
                fields:['fecha','operacion','tip_doc','nro_doc','entrada','salida','saldo','precio','razonsocial','observacion'],
				remoteSort:true,
				sortInfo: {field:'fecha', direction:'asc'},
				listeners:{
					load:function(){
						kardex.fn_calcular();	
					}
				}
            });
			
			var pager = new Ext.PagingToolbar({
                id:kardex.id+'_pager',
                store:store_kardex_lista,
                displayInfo: true,
                displayMsg: '{0} - {1} de {2} Registros',
                emptyMsg: 'No existen registros',
                pageSize:100
            });
			
			pager.on('beforechange',function(bar,params){  
				params.anio = Ext.getCmp(kardex.id+'-txt_anio').getValue();
				params.mon_id = Ext.getCmp(kardex.id+'-combo_monedas').getValue();
				params.pro_id = Ext.getCmp(kardex.id+'-mcd_id').getValue();
			}); 
            		            
            var grid_kardex_lista = new Ext.grid.GridPanel({
                id:kardex.id+'-grid_lista',
                store: store_kardex_lista,
				singleSelect:true,
                forceSelection:true,
                columnLines:true,
				enableHdMenu:false,				 
				autoScroll:true,
                width:'100%',
                stateful: true,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                bbar:pager,
                columns:
                [
                    {header:'Fecha',sortable :true,dataIndex:'fecha',width:80},
                    {header:'Operacion',sortable :true,dataIndex:'operacion',width:90},
                    {header:'Tipo Doc',sortable :true,dataIndex:'tip_doc',width:70},
                    {header:'Nro de Doc',sortable :true,dataIndex:'nro_doc',width:90},
                    {header:'Ingreso',sortable :true,dataIndex:'entrada',width:80,align:'right'},
                    {header:'Egreso',sortable :true,dataIndex:'salida',width:80,align:'right'},
                    {header:'Saldo',sortable :true,dataIndex:'saldo',width:80,align:'right'},
					{header:'Precio',sortable :true,dataIndex:'precio',width:80,align:'right'},
                    {header:'Razon Social',sortable :true,dataIndex:'razonsocial',width:160},
                    {header:'Observacion',sortable :true,dataIndex:'observacion',width:130, hidden:true},
                    ]
            });
			//<<<
            
            var panel = new Ext.Panel({  
            layout: 'border',
			tbar:[{
				xtype: 'toolbar',
				dock: 'top',
				items: [{
						  xtype:'hidden',
						  id:kardex.id+'-mcd_id',
						  value:'0'
						}, txt_anio, combo_monedas, 'Buscar por producto :',txt_producto,btn_producto,btn_imprimir]
				}],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                //layout:'fit',
                xtype: 'panel',
                width:'96%',
				height:'100%',
                autoScroll: true,  
                border:false,
                items:
                [
                    {
						id:kardex.id+'-formulario',
						xtype:'form',
						frame: true,
						layout:'column',
						border:false,
						height:'100px',
						items:
						[
							{
								xtype:'panel',labelWidth:50,layout:'form',
								border:false,columnWidth:1,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-codigoproducto',
										fieldLabel:'Codigo',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'left'},
										width:770,
										readOnly:true
									}
								]
							},
							{
								xtype:'panel',labelWidth:50,layout:'form',
								border:false,columnWidth:0.5,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-marca',
										fieldLabel:'Marca',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'left'},
										width:350,
										readOnly:true
									}
								]
							},
							{
								xtype:'panel',labelWidth:50,layout:'form',
								border:false,columnWidth:0.5,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-linea',
										fieldLabel:'Linea',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'left'},
										width:350,
										readOnly:true
									}
								]
							},
						]
					}, grid_kardex_lista,
					{
						id:kardex.id+'-totales',
						xtype:'form',
						frame: true,
						layout:'column',
						border:false,
						items:
						[
							{
								xtype:'panel',labelWidth:80,layout:'form',
								border:false,columnWidth:.25,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-saldo_anterior',
										fieldLabel:'Saldo Anterior',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'right'},
										width:76,
										readOnly:true
									}
								]
							},
							{
								xtype:'panel',labelWidth:80,layout:'form',
								border:false,columnWidth:.25,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-total_ingresos',
										fieldLabel:'Total Ingresos',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'right'},
										width:76,
										readOnly:true
									}
								]
							},
							{
								xtype:'panel',labelWidth:80,layout:'form',
								border:false,columnWidth:.25,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-total_egresos',
										fieldLabel:'Total Egresos',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'right'},
										width:76,
										readOnly:true
									}
								]
							},
							{
								xtype:'panel',labelWidth:80,layout:'form',
								border:false,columnWidth:.25,
								items:
								[        
									{
										xtype:'textfield',
										id:kardex.id+'-nuevo_saldo',
										fieldLabel:'Nuevo Saldo',
										itemCls: 'label01',
										style:{marginLeft:'0px',textAlign:'right'},
										width:76,
										readOnly:true
									}
								]
							}
						]
					}
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
      		]  
    		});
            
			new Ext.Window({
				id:'win_kardex',
				title:'kardex por Producto',
				width: 900,
				height:600,
				layout:'fit',
				border:false,
				frame:true,
				autoDestroy:true,
				autoScroll:false,
				minimizable: false,
				maximizable: false,
				closable:true,
				collapsible:false,
				draggable:true,
				onEsc:function(){Ext.getCmp('win_kardex').close();}, resizable:true,
				items:panel,
				buttonAlign:'center'
			});
			
			Ext.getCmp('win_kardex').show();
			Ext.getCmp('win_kardex').center();
			Ext.getCmp('win_kardex').toFront();
			Ext.getCmp(kardex.id+'-combo_monedas').setValue('1');
			Ext.getCmp(kardex.id+'-combo_monedas').setRawValue('SOLES');
			
			obj = Ext.getCmp(kardex.id+'_pager').getEl();
			obj = obj.parent();
			obj = obj.prev();
			obj.setStyle('height','405px');
			
        },
				
		fn_imprimir:function()
        {
			document.getElementById('frmReporte-kardex').action="maestros/kardex-lista-impresion";
			document.getElementById('txtpar1').value = Ext.getCmp(kardex.id+'-txt_anio').getValue();
			document.getElementById('txtpar2').value = Ext.getCmp(kardex.id+'-combo_monedas').getValue();
			document.getElementById('txtpar3').value = Ext.getCmp(kardex.id+'-mcd_id').getValue();
			document.getElementById('txtpar4').value = Ext.getCmp(kardex.id+'-txt_producto').getValue();
			document.getElementById('txtpar5').value = Ext.getCmp(kardex.id+'-marca').getValue();
			document.getElementById('txtpar6').value = Ext.getCmp(kardex.id+'-linea').getValue();
			document.getElementById('txtpar7').value = Ext.getCmp(kardex.id+'-combo_monedas').getRawValue();
			
            document.getElementById('frmReporte-kardex').submit();
        },		
        fn_calcular:function()
        {
            var saldo_anterior='0';
			var total_ingresos='0';
            var total_egresos='0';
            var saldo_actual='0';
            var datos='';
            for(i=0;i<Ext.getCmp(kardex.id+'-grid_lista').store.getCount();i++)
            {
                datos=Ext.getCmp(kardex.id+'-grid_lista').getStore(0).getAt(i);
				if(i==0){
					saldo_anterior= Number(datos.get('saldo'));
				}else{
					total_ingresos = Number(total_ingresos) + Number(datos.get('entrada'));
					total_egresos = Number(total_egresos) + Number(datos.get('salida'));
					saldo_actual = Number(datos.get('saldo'));
				}
				
            }
			Ext.getCmp(kardex.id+'-saldo_anterior').setValue(saldo_anterior);
			Ext.getCmp(kardex.id+'-total_ingresos').setValue(total_ingresos);
			Ext.getCmp(kardex.id+'-total_egresos').setValue(total_egresos);
			Ext.getCmp(kardex.id+'-nuevo_saldo').setValue(saldo_actual);
        },    
		
		fn_producto:function()
        {
			//Panel 2>>>
			var btn_cerrar=new Ext.Button({
                id:kardex.id+'-btn_cerrar',
                text:'Cerrar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp('win_buscar_mercaderias_kardex').close();
                        }
                    }
            });
            
            var store_mercaderias_lista_kardex=new Ext.data.JsonStore({
                url:'maestros/mercaderias-lista',
                root:'data',
                totalProperty:'total',
                fields:['mcd_id','codigo1','codigo2','codigo3','nombre','ume_id','mar_id','lin_id','precio_costo','precio_venta','stock_minimo','stock_actual', 'utilidad', 'desc1', 'desc2', 'desc3', 'desc4','activo', 'fam_id', 'ume_nom', 'precio_compra', 'ind_calculo','mar_nom', 'stock_pro', 'nom_lin'],
				remoteSort:true,
				sortInfo: {field:'nombre', direction:'asc'}
            });

            var store_mercaderias_describe=new Ext.data.JsonStore({
                url:'maestros/mercaderias-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });            
            store_mercaderias_describe.load({params:{table:'maestros_mercaderias'}});
			
			var store_lineasbusq_lista=new Ext.data.JsonStore({
                url:'tablas/lineas-lista',
                root:'data',
                totalProperty:'total',
                fields:['lin_id','nombre']
            });
			store_lineasbusq_lista.load();
			var combo_lineas_busq=new Ext.form.ComboBox({
                id:kardex.id+'-combo_lineas_busq',
                store:store_lineasbusq_lista,
                valueField:'lin_id',
                displayField:'nombre',
                triggerAction:'all',
                emptyText:'Linea',
                mode:'local',
                width:200,
                editable:false,
				listeners:
					{
						select:function(cmb,record,index)
						{
							store_mercaderias_lista_kardex.load({params:{lin_id:cmb.getValue(),campo:Ext.getCmp(kardex.id+'-combo_describe_mercaderias').getValue(),query:Ext.getCmp(kardex.id+'-buscar_mercaderia').getValue(),start:0,limit:100}});
						}
					}
            });
            
            var pagerProStock = new Ext.PagingToolbar({
                id:kardex.id+'_pager_kardex',
                store:store_mercaderias_lista_kardex,
                displayInfo: true,
                displayMsg: '{0} - {1} de {2} Registros',
                emptyMsg: 'No existen registros',
                pageSize:100
            });
			
			pagerProStock.on('beforechange',function(bar,params){  
				params.campo = Ext.getCmp(kardex.id+'-combo_describe_mercaderias').getValue();
				params.query = Ext.getCmp(kardex.id+'-buscar_mercaderia').getValue();
				params.lin_id = Ext.getCmp(kardex.id+'-combo_lineas_busq').getValue();
			}); 
            
            var combo_mercaderias_describe=new Ext.form.ComboBox({
                id:kardex.id+'-combo_describe_mercaderias',
                store:store_mercaderias_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
				value:'codigo1',
                mode:'local',
                width:100,
                editable:false
            });
			
			var txt_busqueda_mercaderia = new Ext.app.SearchField({
				id:kardex.id+'-buscar_mercaderia', 
				emptyText : 'Valor a buscar...',
				enableKeyEvents: true,
				store: store_mercaderias_lista_kardex,
				hasSearch : false,
				width: 200,
				listeners:
				{
					specialkey:function(obj, e)
					{
						if (e.getKey() == 13)
						{
						store_mercaderias_lista_kardex.load({params:{lin_id:Ext.getCmp(kardex.id+'-combo_lineas_busq').getValue(),campo:Ext.getCmp(kardex.id+'-combo_describe_mercaderias').getValue(),query:Ext.getCmp(kardex.id+'-buscar_mercaderia').getValue(),start:0,limit:100}});
						}
					}
				}
			});
            
            var grid_mercaderias_lista_kardex = new Ext.grid.GridPanel({
                id:kardex.id+'-grid_mercaderias_lista_kardex',
                store: store_mercaderias_lista_kardex,
                singleSelect:true,
                forceSelection:true,
                columnLines:true,
                monitorResize:true,
                width:580,
                height:400,
                stateful: true,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                bbar:pagerProStock,
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'mcd_id',width:25},
                    {header:'Código 1',sortable :true,dataIndex:'codigo1',width:100},
                    {header:'Código 2',sortable :true,dataIndex:'codigo2',width:100},
                    {header:'Código 3',sortable :true,dataIndex:'codigo3',width:100,hidden:true},
                    {header:'Descripción',sortable :true,dataIndex:'nombre',width:250},
                    {header:'Marca',sortable :true,dataIndex:'mar_nom',width:100},
					{header:'Unidad de Medida',sortable :true,dataIndex:'ume_nom',width:100,hidden:true},
					{header:'Stock Actual',sortable :true,dataIndex:'stock_pro',width:100,align:'right'},
                    {header:'Precio Compra',sortable :true,dataIndex:'precio_compra',width:100,align:'right',hidden:true},
					{header:'Precio Costo',sortable :true,dataIndex:'precio_costo',width:100,align:'right'},
                    {header:'Precio Venta',sortable :true,dataIndex:'precio_venta',width:100,align:'right'},
                    {header:'Stock Mínimo',sortable :true,dataIndex:'stock_minimo',width:100,align:'right',hidden:true},
					{header:'% Incremento',sortable :true,dataIndex:'utilidad',width:100,align:'right',hidden:true},
					{header:'% Desc 1',sortable :true,dataIndex:'desc1',width:100,align:'right',hidden:true},
					{header:'% Desc 2',sortable :true,dataIndex:'desc2',width:100,align:'right',hidden:true},
					{header:'% Desc 3',sortable :true,dataIndex:'desc3',width:100,align:'right',hidden:true},
					{header:'% Desc 4',sortable :true,dataIndex:'desc4',width:100,align:'right',hidden:true},
                    {header:'Estado',sortable :true,dataIndex:'activo',width:100,hidden:true}
                    ],
                listeners:
                {
                    rowdblclick:function()
                    {
                        var rs=Ext.getCmp(kardex.id+'-grid_mercaderias_lista_kardex').getSelectionModel().getSelected();
						
						if(rs)
			            {
							Ext.getCmp(kardex.id+'-mcd_id').setValue(rs.get('mcd_id'));
							Ext.getCmp(kardex.id+'-txt_producto').setValue(rs.get('nombre'));
							Ext.getCmp(kardex.id+'-codigoproducto').setValue(rs.get('codigo1') + ' - ' + rs.get('nombre'));
							Ext.getCmp(kardex.id+'-marca').setValue(rs.get('mar_nom'));
							Ext.getCmp(kardex.id+'-linea').setValue(rs.get('nom_lin'));
							
							Ext.getCmp('win_buscar_mercaderias_kardex').hide();
							Ext.getCmp('win_buscar_mercaderias_kardex').close()
							
							if(Ext.getCmp(kardex.id+'-txt_anio').getValue()<0){
								return;
							}
							if(Ext.getCmp(kardex.id+'-combo_monedas').getValue()==''){
								return;
							}
							
							Ext.getCmp(kardex.id+'-grid_lista').store.removeAll();
							Ext.getCmp(kardex.id+'-grid_lista').store.load({params:{anio:Ext.getCmp(kardex.id+'-txt_anio').getValue(), mon_id:Ext.getCmp(kardex.id+'-combo_monedas').getValue(),pro_id:rs.get('mcd_id'),start:0,limit:100}});
						}else{
							alert('No ha seleccionado ningun producto');
						}
                    }
                }
            });            
            
            var panel2 = new Ext.Panel({  
            	layout: 'border',
				tbar:[
					{
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [combo_lineas_busq,combo_mercaderias_describe,'-',txt_busqueda_mercaderia,'-',btn_cerrar]
                    }
				],
            	bodyStyle:'height:auto;width:650px;margin:auto;',
            	border:false,
            	items: [
            	{  
					region: 'center',
					layout:'fit',
					xtype: 'panel',
					width:'640',
					autoScroll: true,  
					border:false,
					items:
					[
						grid_mercaderias_lista_kardex
						
					]
				}
				]  
    		});
				//<<<
			new Ext.Window({
				id:'win_buscar_mercaderias_kardex',
				title:'Mercaderías',
				width: 650,
				height:500,
				layout:'fit',
				border:false,
				frame:true,
				autoDestroy:true,
				autoScroll:false,
				minimizable: false,
				maximizable: false,
				closable:false,
				collapsible:false,
				draggable:true,
				onEsc:function(){Ext.getCmp('win_buscar_mercaderias_kardex').close();},
				resizable:true,
				items:panel2,
				buttonAlign:'center'
			});
			Ext.getCmp('win_buscar_mercaderias_kardex').show();
			//Ext.getCmp(kardex.id+'-grid_mercaderias_lista_kardex').store.load({params:{start:0,limit:100}});
        }
    }
    Ext.onReady(kardex.init,kardex);

</script>