<form id="frmReporte-producto_excel" name="frmReporte-producto_excel" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
  <input type="hidden" name="txtpar3" id="txtpar3" />
  <input type="hidden" name="txtpar4" id="txtpar4" />
  <input type="hidden" name="txtpar5" id="txtpar5" />
</form>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('rptproducto');
    rptproducto={
        id:'rptproducto',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_guardar=new Ext.Button({
                id:rptproducto.id+'-btn_guardar',
                text:'Exportar a Excel',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            rptproducto.fn_guardar();
                        }
                    }
            });
            
            var store_tienda_lista=new Ext.data.JsonStore({
                url:'maestros/tiendas-lista',
                root:'data',
                totalProperty:'total',
                fields:['tie_id','nombre','descripcion','telefono','direccion','precio','suc_id','estado']
            });

            store_tienda_lista.load({params:{quitar:'SI'}});
			
            var store_marcas_lista=new Ext.data.JsonStore({
                url:'tablas/marcas-lista',
                root:'data',
                totalProperty:'total',
                fields:['mar_id','nombre']
            });
			
			var store_lineas_lista=new Ext.data.JsonStore({
                url:'tablas/lineas-lista',
                root:'data',
                totalProperty:'total',
                fields:['lin_id','nombre']
            });
			store_lineas_lista.load();
            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                xtype:'panel',
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:rptproducto.id+'-usr_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_tienda_lista,
                                id:rptproducto.id+'-tie_id',
                                fieldLabel:'Elegir Tienda a reportar',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:220,
                                mode:'local',
                                valueField:'tie_id',
                                displayField:'nombre',
                                triggerAction:'all',
                                forceSelection:true,
								allowBlank:false
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:90,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_marcas_lista,
                                id:rptproducto.id+'-mar_id',
                                fieldLabel:'Marca',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:250,
                                valueField:'mar_id',
                                displayField:'nombre',
                                triggerAction:'all',
                                forceSelection:true,
								allowBlank:true,
								pageSize:100,
                                listeners:
                                    {
										beforequery:function(obj){
											store_marcas_lista.setBaseParam('campo', 'nombre');
											store_marcas_lista.setBaseParam('query', Ext.getCmp(rptproducto.id+'-mar_id').getValue());						
										},
										expand:function(cmb){
											if(!cmb.getRawValue()){
												store_marcas_lista.load({params:{start:0,limit:100}});
											}
										},
										specialkey:function(obj, e)
										{
											if (e.getKey() == 13)
											{
												store_marcas_lista.load({params:{campo:'nombre',query:obj.getRawValue(),start:0,limit:100}});
											}
										},
										select:function(cmb,record,index)
										{
											Ext.getCmp(rptproducto.id+'-prv_ruc').setValue(record.get('ruc'));
											Ext.getCmp(rptproducto.id+'-prv_codigo').setValue(record.get('codigo'));
										}
									}
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:90,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_lineas_lista,
                                id:rptproducto.id+'-lin_id',
                                fieldLabel:'Línea',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:250,
                                mode:'local',
                                valueField:'lin_id',
                                displayField:'nombre',
								allowBlank:true,
                                triggerAction:'all',
                                forceSelection:true
                            }
                        ]
                    }                    
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_guardar,
                        ]
                    }],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'form',
                xtype: 'panel',
                width:'100%',
                autoScroll: true,  
                border:false,
                items:
                [
                    panel_form
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_rptproducto',
                                        title:'Reporte de Producto', 
                                        width: 400,
                                        height:200,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
										modal:true,
                                        collapsible:false,
                                        draggable:true,
                                        onEsc:function(){Ext.getCmp('win_rptproducto').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_rptproducto').show();
                Ext.getCmp('win_rptproducto').center();
                Ext.getCmp('win_rptproducto').toFront();
                btn_guardar.setVisible(true);
        },
        fn_guardar:function()
        {
         	document.getElementById('frmReporte-producto_excel').action="movimientos/producto-excel";
			document.getElementById('txtpar1').value = Ext.getCmp(rptproducto.id+'-tie_id').getValue();
			document.getElementById('txtpar2').value = Ext.getCmp(rptproducto.id+'-mar_id').getValue();
			document.getElementById('txtpar3').value = Ext.getCmp(rptproducto.id+'-lin_id').getValue();
			document.getElementById('txtpar5').value = Ext.getCmp(rptproducto.id+'-tie_id').getRawValue() + '-' + Ext.getCmp(rptproducto.id+'-mar_id').getRawValue() + '-' + Ext.getCmp(rptproducto.id+'-lin_id').getRawValue();
            document.getElementById('frmReporte-producto_excel').submit();
        }
         
    }
    Ext.onReady(rptproducto.init,rptproducto);

</script>