<form id="frmReporte-tiendas" name="frmReporte-tiendas" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
</form>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('tiendas');
    tiendas={
        id:'tiendas',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_nuevo=new Ext.Button({
                id:tiendas.id+'-btn_nuevo',
                text:'Nuevo',
                iconCls:'btn_add_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(tiendas.id+'-panel_derecho').expand();
				Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(true);
                            tiendas.fn_nuevo();
                        }
                    }
            });
            
            var btn_guardar=new Ext.Button({
                id:tiendas.id+'-btn_guardar',
                text:'Guardar',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            tiendas.fn_guardar();
                        }
                    }
            });
            
            var btn_actualizar=new Ext.Button({
                id:tiendas.id+'-btn_actualizar',
                text:'Actualizar',
                iconCls:'btn_update_log',
                listeners:
                    {
                        click:function()
                        {
                            tiendas.fn_actualizar();
                        }
                    }
            });
            
            var btn_editar=new Ext.Button({
                id:tiendas.id+'-btn_editar',
                text:'Editar',
                iconCls:'btn_edit_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            tiendas.fn_editar();
                        }
                    }
            });
            
            var btn_cancelar=new Ext.Button({
                id:tiendas.id+'-btn_cancelar',
                text:'Cancelar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(tiendas.id+'-panel_derecho').collapse();
							Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(false);
                            tiendas.fn_habilitar(false,0);
                        }
                    }
            });
            
            var btn_eliminar=new Ext.Button({
                id:tiendas.id+'-btn_eliminar',
                text:'Eliminar',
                iconCls:'btn_delete_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
							tiendas.fn_eliminar();
                        }
                    }
            });
			
			var btn_imprimir=new Ext.Button({
                id:tiendas.id+'-btn_imprimir',
                text:'Imprimir',
                icon:'images/icon/printer.png',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea imprimir listado?', function(btn) {
                                if(btn == 'yes')
                                {
                                    tiendas.fn_imprimir();
                                }
                            });

                            
                        }
                    }
            });
            
            var store_tiendas_lista=new Ext.data.JsonStore({
                url:'maestros/tiendas-lista',
                root:'data',
                totalProperty:'total',
                fields:['tie_id','codigo','nombre','ruc','direccion','telefono','activo','tip_per','tip_doc','rep_leg','tipo_per', 'tipo_doc']
            });
            
            store_tiendas_lista.load();
            
            var store_tiendas_describe=new Ext.data.JsonStore({
                url:'maestros/tiendas-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });
            
            store_tiendas_describe.load({params:{table:'tiendas'}});
            
            var combo_tiendas_describe=new Ext.form.ComboBox({
                id:tiendas.id+'-combo_describe',
                store:store_tiendas_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
                mode:'local',
                width:100,
                editable:false
            });
            
            var grid_tiendas_lista = new Ext.grid.GridPanel({
                id:tiendas.id+'-grid_lista',
                store: store_tiendas_lista,
                singleSelect:true,
                columnLines:true,
                monitorResize:true,
                width:226,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'tie_id',width:25},
                    {header:'Código',sortable :true,dataIndex:'codigo',width:70},
                    {header:'Nombre',sortable :true,dataIndex:'nombre',width:100},					
					{header:'Tip Per',sortable :true,dataIndex:'tipo_per',width:80},
					{header:'Tip Doc',sortable :true,dataIndex:'tipo_doc',width:80},
                    {header:'Nro Doc',sortable :true,dataIndex:'ruc',width:100},
                    {header:'Dirección',sortable :true,dataIndex:'direccion',width:70,hidden:true},
                    {header:'Teléfono',sortable :true,dataIndex:'telefono',width:100,hidden:true},
					{header:'Representante legal',sortable :true,dataIndex:'rep_leg',width:100},
                    {header:'Activo',sortable :true,dataIndex:'activo',width:100,hidden:true},
                ],
                listeners:
                {
                    rowdblclick:function()
                    {
                        if(Ext.getCmp(tiendas.id+'-btn_editar').isVisible()){
							Ext.getCmp(tiendas.id+'-panel_derecho').expand();
				Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(true);
                        	tiendas.fn_editar();
						}
                    },
					rowclick:function()
                    {
                        Ext.getCmp(tiendas.id+'-btn_editar').enable();
						Ext.getCmp(tiendas.id+'-btn_eliminar').enable();
                    }
                }
            });
            
            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                id:tiendas.id+'-formulario',
				xtype:'form',
				frame: true,
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:tiendas.id+'-tie_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:tiendas.id+'-codigo',
                                fieldLabel:'Código',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:100,
                                readOnly:true,
								allowBlank:false
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:tiendas.id+'-nombre',
                                fieldLabel:'Nombre',
                                itemCls: 'label01',
								style: {textTransform: "uppercase", marginLeft:"7px"},
                                width:350,
								allowBlank:false
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:130,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype: "radiogroup",
                                fieldLabel: "Tipo de Persona",
                                id: tiendas.id+'-tip_per',
                                style:'margin-left:7px',
                                defaults: {xtype: "radio",name: "tip_per"},
                                columns: [60, 100],
                                items: [
                                    {
                                        id:tiendas.id+'-tip_per_n',
                                        boxLabel: "Natural",name: "tip_per",
                                        inputValue: "N",
                                        checked:true
                                    },
                                    {
                                        id:tiendas.id+'-tip_per_j',
                                        boxLabel: "Juridica",name: "tip_per",
                                        inputValue: "J"
                                    }
                                ],
								listeners : {
									change:function(){
										if(Ext.getCmp(tiendas.id+'-tip_per').getValue().getGroupValue()=='N'){
											 Ext.getCmp(tiendas.id+'-tip_doc_d').setVisible(true);
											 Ext.getCmp(tiendas.id+'-tip_doc_r').setVisible(true);
											 Ext.getCmp(tiendas.id+'-tip_doc').setValue("D");
											 Ext.apply(Ext.getCmp(tiendas.id+'-ruc'),{maxLength:8,minLength:8});
											// Ext.getCmp(tiendas.id+'-ruc').setValue('');
											 Ext.getCmp(tiendas.id+'-ruc').el.dom.maxLength = 8;
										}else{
											 Ext.getCmp(tiendas.id+'-tip_doc_d').setVisible(false);
											 Ext.getCmp(tiendas.id+'-tip_doc_r').setVisible(true);					
											 Ext.getCmp(tiendas.id+'-tip_doc').setValue("R");					
											 Ext.apply(Ext.getCmp(tiendas.id+'-ruc'),{maxLength:11,minLength:11});
											 //Ext.getCmp(tiendas.id+'-ruc').setValue('');
											 Ext.getCmp(tiendas.id+'-ruc').el.dom.maxLength = 11;
											  
										}
									}	
								}
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:130,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype: "radiogroup",
                                fieldLabel: "Tipo de Documento",
                                id: tiendas.id+'-tip_doc',
                                style:'margin-left:7px',
                                defaults: {xtype: "radio",name: "tip_doc"},
                                columns: [60, 100],
                                items: [
                                    {
                                        id:tiendas.id+'-tip_doc_d',
                                        boxLabel: "DNI",name: "tip_doc",
                                        inputValue: "D",
                                        checked:true
                                    },
                                    {
                                        id:tiendas.id+'-tip_doc_r',
                                        boxLabel: "RUC",name: "tip_doc",
                                        inputValue: "R"
                                    }
                                ],
								listeners : {
									change:function(){
										if(Ext.getCmp(tiendas.id+'-tip_per').getValue().getGroupValue()=='N'){
											 Ext.getCmp(tiendas.id+'-tip_doc_d').setVisible(true);
											 Ext.getCmp(tiendas.id+'-tip_doc_r').setVisible(true);
											 Ext.getCmp(tiendas.id+'-tip_doc').setValue("D");
											 Ext.apply(Ext.getCmp(tiendas.id+'-ruc'),{maxLength:8,minLength:8});
											// Ext.getCmp(tiendas.id+'-ruc').setValue('');
											 Ext.getCmp(tiendas.id+'-ruc').el.dom.maxLength = 8;
										}else{
											 Ext.getCmp(tiendas.id+'-tip_doc_d').setVisible(false);
											 Ext.getCmp(tiendas.id+'-tip_doc_r').setVisible(true);					
											 Ext.getCmp(tiendas.id+'-tip_doc').setValue("R");					
											 Ext.apply(Ext.getCmp(tiendas.id+'-ruc'),{maxLength:11,minLength:11});
											 //Ext.getCmp(tiendas.id+'-ruc').setValue('');
											 Ext.getCmp(tiendas.id+'-ruc').el.dom.maxLength = 11;
											  
										}
									}	
								}
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
							new Ext.form.NumberField({
                                /*xtype:'textfield',*/
                                id:tiendas.id+'-ruc',
                                fieldLabel:'Nro Doc',
                                itemCls: 'label01',
                                style:'margin-left:7px',
								maxLength:8,
								minLength:8,
                                width:150,
								allowBlank:false,
								decimalPrecision:0,
								autoCreate: {tag: 'input', type: 'text', size: '20', autocomplete: 'off', maxlength: '8'}
                            })
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:tiendas.id+'-direccion',
                                fieldLabel:'Dirección',
                                itemCls: 'label01',
								style: {textTransform: "uppercase", marginLeft:"7px"},
                                width:350
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:tiendas.id+'-telefono',
                                fieldLabel:'Teléfono',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:150
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:130,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:tiendas.id+'-rep_leg',
                                fieldLabel:'Representante Legal',
                                itemCls: 'label01',
								style: {textTransform: "uppercase", marginLeft:"7px"},
                                width:350
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype: "radiogroup",
                                fieldLabel: "Estado",
                                id: tiendas.id+'-estado',
                                style:'margin-left:7px',
                                defaults: {xtype: "radio",name: "estado"},
                                columns: [60, 100],
                                items: [
                                    {
                                        id:tiendas.id+'-estado_activo',
                                        boxLabel: "Activo",name: "estado",
                                        inputValue: "1",
                                        checked:true
                                    },
                                    {
                                        id:tiendas.id+'-estado_desactivo',
                                        boxLabel: "Desactivado",name: "estado",
                                        inputValue: "0"
                                    }
                                ]
                            }
                        ]
                    },
                    
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_nuevo,'-',btn_guardar,btn_actualizar,btn_editar,'-',btn_eliminar,btn_cancelar, '-', btn_imprimir,
                            combo_tiendas_describe,'-',
                    new Ext.app.SearchField({
                        id:tiendas.id+'-buscar', 
                        emptyText : 'Valor a buscar...',
                        enableKeyEvents: true,
                        store: store_tiendas_lista,
                        hasSearch : false,
                        width: 120,
                        listeners:
                        {
                            specialkey:function(obj, e)
                            {
                                if (e.getKey() == 13)
                                {
									tiendas.fn_habilitar(false,0);
                                store_tiendas_lista.load({params:{campo:Ext.getCmp(tiendas.id+'-combo_describe').getValue(),query:Ext.getCmp(tiendas.id+'-buscar').getValue()}});
                                }
                            }
                        }
                    })
                    
                        ]
                    }],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'fit',
                xtype: 'panel',
                width:'96%',
                autoScroll: true,  
                border:false,
                items:
                [
                    grid_tiendas_lista
                    
                ]
            }
            ,
            {
                region:'center',
                width:'0',
                height:'0'
            }
            ,
            {  
                id:tiendas.id+'-panel_derecho',
                region: 'east',
                xtype: 'panel',
                collapsible:true,
                layout: 'form',
                split:true,
                collapsed:true,
                width:'100%',
                border:false,
                items:
                [
                    panel_form
                ]  
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_tiendas',
                                        title:'Tiendas o Sucursales', 
                                        width: 800,
                                        height:500,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
                                        collapsible:false,
                                        draggable:true,
                                        onEsc:function(){Ext.getCmp('win_tiendas').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
			});
                Ext.getCmp('win_tiendas').show();
                Ext.getCmp('win_tiendas').center();
                Ext.getCmp('win_tiendas').toFront();
                tiendas.fn_habilitar(false,0);
                Ext.getCmp(tiendas.id+'-panel_derecho').collapse();
							Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(false);
        },
        fn_nuevo:function()
        {
			Ext.Msg.wait('Generando código... por favor espere!');
            Ext.Ajax.request({
                    url:'maestros/tiendas-codigo',
                    params:
                    {
                        table:'tiendas'
                    },
                    success:function(response,options)
                    {
						Ext.Msg.hide();						
                        var res = Ext.decode(response.responseText);
                        var numero="0000"+res.AUTO_INCREMENT;
                        var codigo="TI"+numero.substr(numero.length-4,4)
                        Ext.getCmp(tiendas.id+'-codigo').setValue(codigo);
                    }
                });
            Ext.getCmp(tiendas.id+'-tie_id').setValue('');
            Ext.getCmp(tiendas.id+'-codigo').setValue('');
            Ext.getCmp(tiendas.id+'-nombre').setValue('');
			
			Ext.getCmp(tiendas.id+'-tip_per').items.items[0].setValue(true);
            Ext.getCmp(tiendas.id+'-tip_per').items.items[1].setValue(false);
			
			Ext.getCmp(tiendas.id+'-tip_doc').items.items[0].setValue(true);
            Ext.getCmp(tiendas.id+'-tip_doc').items.items[1].setValue(false);
			
            Ext.getCmp(tiendas.id+'-ruc').setValue('');
            Ext.getCmp(tiendas.id+'-direccion').setValue('');
            Ext.getCmp(tiendas.id+'-telefono').setValue('');
			Ext.getCmp(tiendas.id+'-rep_leg').setValue('');
            Ext.getCmp(tiendas.id+'-estado').items.items[0].setValue(true);
            Ext.getCmp(tiendas.id+'-estado').items.items[1].setValue(false);
            Ext.getCmp(tiendas.id+'-codigo').focus(true,10);
            tiendas.fn_habilitar(true,1);
        },
        fn_editar:function()
        {
            var rs=Ext.getCmp(tiendas.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.getCmp(tiendas.id+'-panel_derecho').expand();
				Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(true);
                Ext.getCmp(tiendas.id+'-tie_id').setValue(rs.get('tie_id'));
                Ext.getCmp(tiendas.id+'-codigo').setValue(rs.get('codigo'));
                Ext.getCmp(tiendas.id+'-nombre').setValue(rs.get('nombre'));
				
				Ext.getCmp(tiendas.id+'-tip_per').setValue('N');
				if(rs.get('tip_per')!=null){
					Ext.getCmp(tiendas.id+'-tip_per').setValue(rs.get('tip_per'));
					if(rs.get('tip_per')=='N'){
						 Ext.getCmp(tiendas.id+'-tip_doc_d').setVisible(true);
						 Ext.getCmp(tiendas.id+'-tip_doc_r').setVisible(true);
						 Ext.getCmp(tiendas.id+'-tip_doc').setValue("D");
						 Ext.apply(Ext.getCmp(tiendas.id+'-ruc'),{maxLength:8,minLength:8});
						 Ext.getCmp(tiendas.id+'-ruc').el.dom.maxLength = 8;
					}else{
						 Ext.getCmp(tiendas.id+'-tip_doc_d').setVisible(true);
						 Ext.getCmp(tiendas.id+'-tip_doc_r').setVisible(true);
						 Ext.getCmp(tiendas.id+'-tip_doc').setValue("D");
						 Ext.apply(Ext.getCmp(tiendas.id+'-ruc'),{maxLength:11,minLength:11});
						 Ext.getCmp(tiendas.id+'-ruc').el.dom.maxLength = 11;				
					}
				}				
				if(rs.get('tip_doc')!=null){
					Ext.getCmp(tiendas.id+'-tip_doc').setValue(rs.get('tip_doc'));
				}
				
                Ext.getCmp(tiendas.id+'-ruc').setValue(rs.get('ruc'));
                Ext.getCmp(tiendas.id+'-direccion').setValue(rs.get('direccion'));
                Ext.getCmp(tiendas.id+'-telefono').setValue(rs.get('telefono'));
				Ext.getCmp(tiendas.id+'-rep_leg').setValue(rs.get('rep_leg'));
                Ext.getCmp(tiendas.id+'-estado').setValue(rs.get('activo'));
                
                tiendas.fn_habilitar(true,2);
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
        fn_actualizar:function()
        {
            if(tiendas.fn_validar()){
				Ext.getCmp(tiendas.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'maestros/tiendas-actualizar',
					params:{ 
						tie_id:Ext.getCmp(tiendas.id+'-tie_id').getValue(),
						codigo:Ext.getCmp(tiendas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(tiendas.id+'-nombre').getValue().toUpperCase(),
						tip_per:Ext.getCmp(tiendas.id+'-tip_per').getValue().getGroupValue(),
						tip_doc:Ext.getCmp(tiendas.id+'-tip_doc').getValue().getGroupValue(),
						ruc:Ext.getCmp(tiendas.id+'-ruc').getValue(),
						direccion:Ext.getCmp(tiendas.id+'-direccion').getValue().toUpperCase(),
						telefono:Ext.getCmp(tiendas.id+'-telefono').getValue(),
						rep_leg:Ext.getCmp(tiendas.id+'-rep_leg').getValue().toUpperCase(),
						estado:Ext.getCmp(tiendas.id+'-estado').getValue().getGroupValue()
					},
					waitTitle: 'Actualizando Informacion',
					waitMsg: 'Enviando datos..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(tiendas.id+'-panel_derecho').collapse();
							Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							tiendas.fn_habilitar(false,0);
							Ext.getCmp(tiendas.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(tiendas.id+'-combo_describe').getValue(),query:Ext.getCmp(tiendas.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(tiendas.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(tiendas.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(tiendas.id+res.campo).focus(true,10);
					}
				});
				/*Ext.Ajax.request({
					url:'maestros/tiendas-actualizar',
					params:
					{
						tie_id:Ext.getCmp(tiendas.id+'-tie_id').getValue(),
						codigo:Ext.getCmp(tiendas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(tiendas.id+'-nombre').getValue().toUpperCase(),
						tip_per:Ext.getCmp(tiendas.id+'-tip_per').getValue().getGroupValue(),
						tip_doc:Ext.getCmp(tiendas.id+'-tip_doc').getValue().getGroupValue(),
						ruc:Ext.getCmp(tiendas.id+'-ruc').getValue(),
						direccion:Ext.getCmp(tiendas.id+'-direccion').getValue().toUpperCase(),
						telefono:Ext.getCmp(tiendas.id+'-telefono').getValue(),
						rep_leg:Ext.getCmp(tiendas.id+'-rep_leg').getValue().toUpperCase(),
						estado:Ext.getCmp(tiendas.id+'-estado').getValue().getGroupValue()
					},
					success:function(response,options)
					{             
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(tiendas.id+'-panel_derecho').collapse();
							Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							tiendas.fn_habilitar(false,0);
							Ext.getCmp(tiendas.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(tiendas.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
        fn_guardar:function()
        {
            if(tiendas.fn_validar()){
				Ext.getCmp(tiendas.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'maestros/tiendas-guardar',
					params:{ 
						codigo:Ext.getCmp(tiendas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(tiendas.id+'-nombre').getValue().toUpperCase(),
						tip_per:Ext.getCmp(tiendas.id+'-tip_per').getValue().getGroupValue(),
						tip_doc:Ext.getCmp(tiendas.id+'-tip_doc').getValue().getGroupValue(),
						ruc:Ext.getCmp(tiendas.id+'-ruc').getValue(),
						direccion:Ext.getCmp(tiendas.id+'-direccion').getValue().toUpperCase(),
						telefono:Ext.getCmp(tiendas.id+'-telefono').getValue(),
						rep_leg:Ext.getCmp(tiendas.id+'-rep_leg').getValue().toUpperCase(),
						estado:Ext.getCmp(tiendas.id+'-estado').getValue().getGroupValue()
					},
					waitTitle: 'Registro de ',
					waitMsg: 'Guardando Información..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(tiendas.id+'-panel_derecho').collapse();
							Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							tiendas.fn_habilitar(false,0);
							Ext.getCmp(tiendas.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(tiendas.id+'-combo_describe').getValue(),query:Ext.getCmp(tiendas.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(tiendas.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(tiendas.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(tiendas.id+res.campo).focus(true,10);							
					}
				});
				/*Ext.Msg.wait('Guardando información... por favor espere!');
				Ext.Ajax.request({
					url:'maestros/tiendas-guardar',
					params:
					{
						codigo:Ext.getCmp(tiendas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(tiendas.id+'-nombre').getValue().toUpperCase(),
						tip_per:Ext.getCmp(tiendas.id+'-tip_per').getValue().getGroupValue(),
						tip_doc:Ext.getCmp(tiendas.id+'-tip_doc').getValue().getGroupValue(),
						ruc:Ext.getCmp(tiendas.id+'-ruc').getValue(),
						direccion:Ext.getCmp(tiendas.id+'-direccion').getValue().toUpperCase(),
						telefono:Ext.getCmp(tiendas.id+'-telefono').getValue(),
						rep_leg:Ext.getCmp(tiendas.id+'-rep_leg').getValue().toUpperCase(),
						estado:Ext.getCmp(tiendas.id+'-estado').getValue().getGroupValue()
					},
					success:function(response,options)
					{             
						Ext.Msg.hide();
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(tiendas.id+'-panel_derecho').collapse();
							Ext.getCmp(tiendas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							tiendas.fn_habilitar(false,0);
							Ext.getCmp(tiendas.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(tiendas.id+res.campo).focus(true,10);							
						}						
					}
				});*/
			}
        },
        fn_eliminar:function()
        {
            var rs=Ext.getCmp(tiendas.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.Msg.confirm('Alerta', 'Desea eliminar?', function(btn) {
					if(btn == 'yes')
					{
						Ext.Msg.wait('Eliminando... por favor espere!');
						Ext.Ajax.request({
							url:'maestros/tiendas-eliminar',
							params:
							{
								tie_id:rs.get('tie_id')
							},
							success:function(response,options)
							{          
								Ext.Msg.hide();   
								var res = Ext.decode(response.responseText);
								if(res.success){
									og.msg("Ok","El registro se ha eliminado");
									tiendas.fn_habilitar(false,0);
									Ext.getCmp(tiendas.id+'-grid_lista').store.load();
								}else{
									og.msg("Error",res.mensaje);
									Ext.getCmp(tiendas.id+res.campo).focus(true,10);							
								}
							}
						});
					}
				 });
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
		
		fn_validar:function(){
			if(!Ext.getCmp(tiendas.id+'-codigo').isValid())
            {
                og.msg("Error", "Ingrese el campo Código");
                Ext.getCmp(tiendas.id+'-codigo').focus(true,10);
                return false;
            }
            if(!Ext.getCmp(tiendas.id+'-nombre').isValid())
            {
                og.msg("Error", "Ingrese el campo Nombre");
                Ext.getCmp(tiendas.id+'-nombre').focus(true,10);
                return false;
            }
            if(!Ext.getCmp(tiendas.id+'-ruc').isValid())
            {
                og.msg("Error", "Ingrese el campo Ruc");
                Ext.getCmp(tiendas.id+'-ruc').focus(true,10);
                return false;
            }
            /*if(!Ext.getCmp(tiendas.id+'-direccion').isValid())
            {
                og.msg("Error", "Ingrese el campo Dirección");
                Ext.getCmp(tiendas.id+'-direccion').focus(true,10);
                return false;
            }
            if(!Ext.getCmp(tiendas.id+'-telefono').isValid())
            {
                og.msg("Error", "Ingrese el campo Teléfono");
                Ext.getCmp(tiendas.id+'-telefono').focus(true,10);
                return false;
            }*/
			return true;
		},
		
		fn_imprimir:function()
        {
			document.getElementById('frmReporte-tiendas').action="maestros/tiendas-lista-impresion";
			document.getElementById('txtpar1').value = Ext.getCmp(tiendas.id+'-combo_describe').getValue();
			document.getElementById('txtpar2').value = Ext.getCmp(tiendas.id+'-buscar').getValue();
            document.getElementById('frmReporte-tiendas').submit();
        },
		
		fn_habilitar:function(sw, tipo)
        {
			if(!sw){
				Ext.getCmp(tiendas.id+'-btn_guardar').setVisible(sw);
				Ext.getCmp(tiendas.id+'-btn_actualizar').setVisible(sw);
			}else{
				if(tipo==1){
					Ext.getCmp(tiendas.id+'-btn_guardar').setVisible(sw);
					Ext.getCmp(tiendas.id+'-btn_actualizar').setVisible(!sw);
				}else{
					Ext.getCmp(tiendas.id+'-btn_guardar').setVisible(!sw);
					Ext.getCmp(tiendas.id+'-btn_actualizar').setVisible(sw);
				}
			}
			<?php if($this->acceso[1]=='Y'){?>
			Ext.getCmp(tiendas.id+'-btn_nuevo').setVisible(!sw);			
			<? } ?>
			Ext.getCmp(tiendas.id+'-btn_cancelar').setVisible(sw);
			<?php if($this->acceso[2]=='Y'){?>
			Ext.getCmp(tiendas.id+'-btn_editar').setVisible(!sw);
			<? } ?>
			<?php if($this->acceso[3]=='Y'){?>
			Ext.getCmp(tiendas.id+'-btn_eliminar').setVisible(!sw);
			<? } ?>

			Ext.getCmp(tiendas.id+'-btn_editar').disable();
			Ext.getCmp(tiendas.id+'-btn_eliminar').disable();
			
			Ext.getCmp(tiendas.id+'-buscar').setVisible(!sw);			
			Ext.getCmp(tiendas.id+'-combo_describe').setVisible(!sw);
			
			Ext.getCmp(tiendas.id+'-btn_imprimir').setVisible(!sw);			
        }
         
    }
    Ext.onReady(tiendas.init,tiendas);

</script>