<form id="frmReporte-compras" name="frmReporte-compras" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
  <input type="hidden" name="txtpar3" id="txtpar3" />
  <input type="hidden" name="txtpar4" id="txtpar4" />
  <input type="hidden" name="txttitulo" id="txttitulo" />
  <input type="hidden" name="txtfiltro" id="txtfiltro" />
  <input type="hidden" name="txtsort" id="txtsort" />
  <input type="hidden" name="txtdir" id="txtdir" />
</form>
<?php
$fecha_cambiada = mktime(0,0,0,date("m")-1,date("d"),date("Y"));
$fecha_atras = date("d/m/Y", $fecha_cambiada);
?>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('compras');
    compras={
        id:'compras',
        store_reader:new Ext.data.ArrayStore({  //step 1
            id:compras.id+'-reader_guiasasignadas',
            fields:[{name:'itemid'},{name:'id'},{name:'cantidad'},{name:'codigo'},{name:'detalle'},{name:'marca'},{name:'precio'},{name:'descuento'},{name:'total'},{name:'ume_id'},{name:'valor_desc'},{name:'valor_bruto'}, {name:'ind_calc'}]  
            }),
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_nuevo=new Ext.Button({
                id:compras.id+'-btn_nuevo',
                text:'Nuevo',
                iconCls:'btn_add_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(compras.id+'-panel_derecho').expand();
				Ext.getCmp(compras.id+'-panel_derecho').setVisible(true);
                            compras.fn_nuevo();
                        }
                    }
            });
            
            var btn_guardar=new Ext.Button({
                id:compras.id+'-btn_guardar',
                text:'Guardar',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            compras.fn_guardar();
                        }
                    }
            });
            
            var btn_actualizar=new Ext.Button({
                id:compras.id+'-btn_actualizar',
                text:'Actualizar',
                iconCls:'btn_update_log',
                listeners:
                    {
                        click:function()
                        {
                            compras.fn_actualizar();
                        }
                    }
            });
            
            var btn_editar=new Ext.Button({
                id:compras.id+'-btn_editar',
                text:'Editar',
                iconCls:'btn_edit_log',
                listeners:
                    {
                        click:function()
                        {
                            compras.fn_editar();
                        }
                    }
            });
            
            var btn_cancelar=new Ext.Button({
                id:compras.id+'-btn_cancelar',
                text:'Cancelar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(compras.id+'-panel_derecho').collapse();
							Ext.getCmp(compras.id+'-panel_derecho').setVisible(false);
                            compras.fn_habilitar(false,0);
                        }
                    }
            });
            
            var btn_anular=new Ext.Button({
                id:compras.id+'-btn_anular',
                text:'Anular',
                icon:'images/icon/btn_cancelar.png',
                listeners:
                    {
                        click:function()
                        {
							compras.fn_anular();
                        }
                    }
            });
			
			var btn_eliminar=new Ext.Button({
                id:compras.id+'-btn_eliminar',
                text:'Eliminar',
                iconCls:'btn_delete_log',
                listeners:
                    {
                        click:function()
                        {
							compras.fn_eliminar();
                        }
                    }
            });
			
			var btn_imprimir=new Ext.Button({
                id:compras.id+'-btn_imprimir',
                text:'Imprimir',
                icon:'images/icon/printer.png',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea imprimir listado?', function(btn) {
                                if(btn == 'yes')
                                {
                                    compras.fn_imprimir();
                                }
                            });
                        }
                    }
            });
			
			var btn_busprv=new Ext.Button({
                id:compras.id+'-btn_busprv',
                text:'Buscar',
                listeners:
                    {
                        click:function()
                        {
							//alert(vgVentana);
							vgVentana = 'compras';
                           inicio.getForm( 'maestros/buscaproveedores','Busca Clientes')
                        }
                    }
            });

            var store_compras_lista=new Ext.data.JsonStore({
                url:'movimientos/compras-lista',
                root:'data',
                totalProperty:'total',
                fields:['nombre_proveedor','descripcion_documento','mco_id','codigo','prv_id','tipo_ingreso','doc_id','doc_n','n_guia','cpa_id','mon_id','valor_compra','impuesto_igv','total_compra', 'fec_ven', 'fec_mov', 'moneda', 'prv_codigo', 'ruc', 'anulado', 'afecta', 'formato', 'observacion', 'codigo_prv', 'ruc_prv', 'tipo_cambio', 'condicion', 'abrev_moneda'],
				remoteSort:true,				
				sortInfo: {field:'fec_ven', direction:'desc'}
            });
			
			var pager = new Ext.PagingToolbar({
                id:compras.id+'_pager',
                store:store_compras_lista,
                displayInfo: true,
                displayMsg: '{0} - {1} de {2} Registros',
                emptyMsg: 'No existen registros',
                pageSize:100
            });
			
			pager.on('beforechange',function(bar,params){
				params.fec_ini = Ext.getCmp(compras.id+'-fec_ini').getValue();
				params.fec_fin = Ext.getCmp(compras.id+'-fec_fin').getValue();
				params.doc_id = Ext.getCmp(compras.id+'-doc_id_buscar').getValue();
			});
            
            var vstore_proveedores_lista=new Ext.data.JsonStore({
                url:'maestros/proveedores-lista',
                root:'data',
                totalProperty:'total',
                fields:['prv_id','nombre','ruc','codigo']
            });
            
            //vstore_proveedores_lista.load({params:{start:0,limit:100}});
			
			var pagerCmbPrv = new Ext.PagingToolbar({
                id:compras.id+'_pagerCmbPrb',
                store:vstore_proveedores_lista,
                displayInfo: true,
                displayMsg: '{0} - {1} de {2} Registros',
                emptyMsg: 'No existen registros',
                pageSize:100
            });
			
			pagerCmbPrv.on('beforechange',function(bar,params){  
				params.campo = 'nombre';
				params.query = Ext.getCmp(compras.id+'-combo_prv').getValue();
			});
            
            var store_monedas_lista=new Ext.data.JsonStore({
                url:'tablas/monedas-lista',
                root:'data',
                totalProperty:'total',
                fields:['mon_id','nombre']
            });
            
            store_monedas_lista.load();

            var store_documentos_lista=new Ext.data.JsonStore({
                url:'tablas/documentos-lista',
                root:'data',
                totalProperty:'total',
                fields:['doc_id','abrev','descripcion','ventas','compras','n_ventas','n_compras','nn_credito','nn_debito','str_serie_n_compras','str_n_compras','str_serie_n_ventas','str_n_ventas','str_serie_nn_credito','str_nn_credito','str_serie_nn_debito','str_nn_debito']
            });
            
            store_documentos_lista.load({params:{campo:'compras',query:'SI'}});
            
            var store_condiciones_pago_lista=new Ext.data.JsonStore({
                url:'tablas/condiciones-pago-lista',
                root:'data',
                totalProperty:'total',
                fields:['cpa_id','codigo','descripcion','dias','letras']
            });
            
            store_condiciones_pago_lista.load();
            
            var grid_compras_lista = new Ext.grid.GridPanel({
                id:compras.id+'-grid_lista',
                store: store_compras_lista,
                singleSelect:true,
				forceSelection:true,
                columnLines:true,
                monitorResize:true,
                width:226,
                height:300,
				stateful: true,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
				bbar:pager,
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'mco_id',width:25},
					{header:'Fecha',sortable :true,dataIndex:'fec_ven',width:70},
                    {header:'Doc',sortable :true,dataIndex:'descripcion_documento',width:30},
					{header:'Número',sortable :true,dataIndex:'doc_n',width:80, align:'center'},
					{header:'Cod. Prov',sortable :true,dataIndex:'prv_codigo',width:50, align:'center'},
					{header:'RUC Prov',sortable :true,dataIndex:'ruc_prv',width:80, align:'center'},
					{header:'Proveedor',sortable :true,dataIndex:'nombre_proveedor',width:200},
					{header:'Forma Pago',sortable :true,dataIndex:'condicion',width:65},
					{header:'Compra',sortable :true,dataIndex:'valor_compra',width:70, align:'right'},
					{header:'IGV',sortable :true,dataIndex:'impuesto_igv',width:70, align:'right'},
                    {header:'Total',sortable :true,dataIndex:'total_compra',width:70, align:'right'},
					{header:'Moneda',sortable :true,dataIndex:'abrev_moneda',width:30, align:'left'},
					{header:'Anulado',sortable :true,dataIndex:'anulado',width:50, align:'left'},
					{header:'T.Cambio',sortable :true,dataIndex:'tipo_cambio',width:80, align:'left'}
                ]
                ,
                listeners:
                {
                    rowdblclick:function()
                    {
                        Ext.getCmp(compras.id+'-panel_derecho').expand();
				Ext.getCmp(compras.id+'-panel_derecho').setVisible(true);
                        compras.fn_editar();
                    },
					rowclick:function()
                    {
                        Ext.getCmp(compras.id+'-btn_editar').enable();
						Ext.getCmp(compras.id+'-btn_eliminar').enable();
						Ext.getCmp(compras.id+'-btn_anular').enable();
                    }
                }
            });

            
            var grid_guiasAsignadas=new Ext.grid.EditorGridPanel({
                             //tabIndex:27,
                             id:compras.id+'-guias_asignadas',
                             store: compras.store_reader,
                             clicksToEdit: 1,
                             singleSelect:true,
                             columnLines:true,
                             /*monitorResize:true,*/
                             enableKeyEvents: true,
                             viewConfig:{forceFit:true},
                             /*autoScroll:true,
                             autoHeight:true,*/
                             height:150,
                             listeners:
                                 {
                                    afteredit:function()
                                    {
                                        compras.calcular();
                                    }
                                 },
                             columns:
                             [
                                {
                                  header:"Item", width: 20, sortable: true, dataIndex: 'itemid'},
                                {
                                  header:"Cantidad", width: 30, sortable: true, dataIndex: 'cantidad',align:'right',
                                  editor: new Ext.form.TextField(
                                  {
									  	style:{textAlign:'right'},
                                        enableKeyEvents: true,
										selectOnFocus:true,
										listeners : {
											change : function(obj, eve){
												var index = grid_guiasAsignadas.getSelectionModel().getSelectedCell();
												if (!index)
												{
													return false;
												}												   
												datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(index[0]);
												
												/*if(datos.get('ind_cal')==2){
													vValor = Number(datos.get('total')) / Number(obj.getValue());													
													vDesc = datos.get('descuento');
													var n=vDesc.split("+");
													if(n==0){
														vValor = (100 * vValor) / ( 100 - Number(vDesc));
														vValor = Math.round(vValor*100)/100;	
													}else{
														for(i=n.length - 1;i>=0;i--){
															vValor =(100 * vValor) / ( 100 - Number(n[i]));
															vValor = Math.round(vValor*100)/100;	
														}
													}
													datos.set('precio',vValor);
													datos.set('valor_bruto',vValor * Number(obj.getValue()));
													datos.set('valor_desc',Number(datos.get('total')) - vValor * Number(obj.getValue()));
												}else{
													vValor = Number(obj.getValue()) * Number(datos.get('precio'));
													
													vBruto = vValor;
													datos.set('valor_bruto',vBruto);
													
													vDesc = datos.get('descuento');
													var n=vDesc.split("+");
													if(n==0){
														vValor = vValor - (vValor*Number(vDesc))/100;
														vValor = Math.round(vValor*100)/100;	
													}else{
														for(i=0;i<n.length;i++){
															vValor = vValor - (vValor*Number(n[i]))/100;
															vValor = Math.round(vValor*100)/100;	
														}
													}
													datos.set('valor_desc',vBruto - vValor);
													datos.set('total',vValor);
												}*/
												//compras.calcular();
											},
											specialkey:function(obj,e)
											{
												if(e.getKey() == 13)
												{
													//Ext.getCmp(compras.id+'-guias_asignadas').startEditing(1,5);
													return false;
												}
											}
										}
                                   })
                                },
                                {
                                  header:"Código", width: 40, sortable: true, dataIndex: 'codigo'},
                                {
                                  header:"Detalle", width: 120, sortable: true, dataIndex: 'detalle'},
                                {
                                  header:"Marca", width: 40, sortable: true, dataIndex: 'marca'},
                                {
                                  header:"Precio", width: 50, sortable: true, dataIndex: 'precio',align:'right',
                                  editor: new Ext.form.NumberField(
                                  {
                                        style:{textAlign:'right'},
                                        enableKeyEvents: true,
										selectOnFocus:true,
										listeners : {
											focus : function(obj, eve){
												var index = grid_guiasAsignadas.getSelectionModel().getSelectedCell();
												if (!index)
												{
													return false;
												}												   
												datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(index[0]);
												datos.set('ind_cal',1);
												/*vValor = Number(datos.get('cantidad')) * Number(obj.getValue());
												vBruto = vValor;
												vBruto = Math.round(vBruto*100)/100;	
												datos.set('valor_bruto',vBruto);
												datos.set('ind_cal',1);
												
												vDesc = datos.get('descuento');
												var n=vDesc.split("+");
												if(n==0){
													vValor = vValor - (vValor*Number(vDesc))/100;
													vValor = Math.round(vValor*100)/100;	
												}else{
													for(i=0;i<n.length;i++){
														vValor = vValor - (vValor*Number(n[i]))/100;
														vValor = Math.round(vValor*100)/100;	
													}
												}
												datos.set('valor_desc',vBruto - vValor);
												datos.set('total',vValor);*/
												//compras.calcular();
											},
											specialkey:function(obj,e)
											{
												if(e.getKey() == 13)
												{
													//e.setKey(9);
													return false;
												}
											}
										}
                                   })
                                },
                                {
                                  header:"Desc. %", width: 40, sortable: true, dataIndex: 'descuento',align:'right',
                                  editor: new Ext.form.TextField(
                                  {
									  style:{textAlign:'right'},
                                        enableKeyEvents: true,
										selectOnFocus:true,
										listeners : {
											change : function(obj, eve){
												var index = grid_guiasAsignadas.getSelectionModel().getSelectedCell();
												if (!index)
												{
													return false;
												}												   
												datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(index[0]);
												
												/*if(datos.get('ind_cal')==2){
													vValor = Number(datos.get('total')) / Number(datos.get('cantidad'));
													datos.set('ind_cal',2);
													
													vDesc = obj.getValue();
													var n=vDesc.split("+");
													if(n==0){
														vValor = (100 * vValor) / ( 100 - Number(vDesc));
														vValor = Math.round(vValor*100)/100;	
													}else{
														for(i=n.length - 1;i>=0;i--){
															vValor =(100 * vValor) / ( 100 - Number(n[i]));
															vValor = Math.round(vValor*100)/100;	
														}
													}
													datos.set('precio',vValor);
													datos.set('valor_bruto',vValor * Number(datos.get('cantidad')));
													datos.set('valor_desc',Number(datos.get('total')) - vValor * Number(datos.get('cantidad')));
												}else{
													vValor = Number(datos.get('cantidad')) * Number(datos.get('precio'));
													vBruto = vValor;
													datos.set('valor_bruto',vBruto);
													
													vDesc = obj.getValue();
													var n=vDesc.split("+");
													if(n==0){
														vValor = vValor - (vValor*Number(vDesc))/100;
														vValor = Math.round(vValor*100)/100;	
													}else{
														for(i=0;i<n.length;i++){
															vValor = vValor - (vValor*Number(n[i]))/100;
															vValor = Math.round(vValor*100)/100;	
														}
													}
													datos.set('valor_desc',vBruto - vValor);
													datos.set('total',vValor);
												}*/
												//compras.calcular();
											},
											specialkey:function(obj,e)
											{
												if(e.getKey() == 13)
												{
													//e.setKey(9);
													return false;
												}
											}
										}                          
                                   })
                                },
								{
                                  header:"Total", width: 60, sortable: true, dataIndex: 'total',align:'right',
                                  editor: new Ext.form.NumberField(
                                  {
                                        style:{textAlign:'right'},
                                        enableKeyEvents: true,
										selectOnFocus:true,
										listeners : {
											focus : function(obj, eve){
												var index = grid_guiasAsignadas.getSelectionModel().getSelectedCell();
												if (!index)
												{
													return false;
												}												   
												datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(index[0]);
												
												//vValor = Number(obj.getValue()) / Number(datos.get('cantidad'));
												datos.set('ind_cal',2);
												//alert(vValor);
												//alert(datos.get('descuento'));
												/*vDesc = datos.get('descuento');
												var n=vDesc.split("+");
												if(n==0){
													vDesc = Number(vDesc);
													vValor = (100 * vValor) / ( 100 - Number(vDesc));
													vValor = Math.round(vValor*100)/100;	
												}else{
													vDesc = 1;
													for(i=n.length - 1;i>=0;i--){
														vValor =(100 * vValor) / ( 100 - Number(n[i]));
														vValor = Math.round(vValor*100)/100;	
													}
												}
												//alert('Descto :' + Number(vDesc))
												alert('Precio :' + vValor);
												datos.set('precio',vValor);
												
												if(vDesc==0){
													datos.set('valor_bruto',obj.getValue());
													datos.set('valor_desc',0);
												}else{
													datos.set('valor_bruto',vValor * Number(datos.get('cantidad')));
													datos.set('valor_desc',obj.getValue() - vValor * Number(datos.get('cantidad')));
												}
												alert(vValor);*/
												//compras.calcular();
											},
											specialkey:function(obj,e)
											{
												if(e.getKey() == 13)
												{
													//e.setKey(9);
													return false;
												}
											}
										}
                                   })
                                }
								
                               ]
                             ,
                             tbar:
                               [
                                  {
                                     xtype:'button',
                                     text:'Añadir',
                                     iconCls:'btn_add_log',
                                     listeners:
                                     {
                                       click:function()
                                       {
									   	compras.fn_buscar_producto();
                                          
                                        }
                                  }
                                }
                                  ,
                                  {
                                     xtype:'button',
                                     text:'Quitar',
                                     iconCls:'btn_delete_log',
                                     listeners:
                                     {
                                       click:function()
                                       {
                                          var index = grid_guiasAsignadas.getSelectionModel().getSelectedCell();
                                          if (!index)
                                          {
                                              return false;
                                          }
                                          var rec =  compras.store_reader.getAt(index[0]);
                                           compras.store_reader.remove(rec);
                                           
                                           compras.calcular();
                                           
                                           
                                       }
                                     }
                                  },
                                    
                                     ]
                                }); 

            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
				id:compras.id+'-formulario',
				xtype:'form',
				frame: true,
                layout:'column',
                border:false,
                items:
                [
					{
                      xtype:'hidden',
                      id:compras.id+'-mco_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:.7,
                        items:
                        [
                            
                            {
                                xtype: "radiogroup",
                                fieldLabel: "Tipo de Compra",
                                itemCls: 'label01',
                                id: compras.id+'-tipo_ingreso',
                                style:'margin-left:7px',
                                defaults: {xtype: "radio",name: "tipo_ingreso"},
                                columns: [120,120,120],
                                items: [
                                    {
                                        id:compras.id+'-tipo_ingreso1',
                                        boxLabel: "COMPRA PLAZA",name: "tipo_ingreso",
                                        inputValue: "1",
                                        checked:true
                                    },
                                    {
                                        id:compras.id+'-tipo_ingreso2',
                                        boxLabel: "IMPORTACIÓN",name: "tipo_ingreso",
                                        inputValue: "2"
                                    }/*,
                                    {
                                        id:compras.id+'-tipo_ingreso3',
                                        boxLabel: "TRASLADO",name: "tipo_ingreso",
                                        inputValue: "3"
                                    }*/
                                ]
                            }    
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:70,layout:'form',
                        border:false,columnWidth:.3,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:compras.id+'-codigo',
                                fieldLabel:'Operación',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:120,
								readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:.38,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:vstore_proveedores_lista,
                                id:compras.id+'-prv_id',
                                fieldLabel:'Proveedor',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:220,
                                valueField:'prv_id',
                                displayField:'nombre',
                                triggerAction:'all',
								allowBlank:false,
								pageSize:100,
                                listeners:
                                    {
										beforequery:function(obj){
											vstore_proveedores_lista.setBaseParam('campo', 'nombre');
											vstore_proveedores_lista.setBaseParam('query', Ext.getCmp(compras.id+'-prv_id').getValue());						
										},
										specialkey:function(obj, e)
										{
											if (e.getKey() == 13)
											{
												vstore_proveedores_lista.load({params:{campo:'nombre',query:obj.getRawValue(),start:0,limit:100}});
											}
										},
                                        select:function(cmb,record,index)
                                        {
                                            Ext.getCmp(compras.id+'-prv_ruc').setValue(record.get('ruc'));
                                            Ext.getCmp(compras.id+'-prv_codigo').setValue(record.get('codigo'));
                                        }
                                    }
                            }
                        ]
                    },
					{
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:.07,
                        items:
                        [
                            btn_busprv
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:.25,
                        items:
                        [
                            {
                                xtype:'textfield',
                                fieldLabel:'RUC/DNI',
                                id:compras.id+'-prv_ruc',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:100,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:70,layout:'form',
                        border:false,columnWidth:.30,
                        items:
                        [
                            {
                                xtype:'textfield',
                                fieldLabel:'Código',
                                id:compras.id+'-prv_codigo',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:110,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:.42,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_documentos_lista,
                                id:compras.id+'-doc_id',
                                fieldLabel:'Documento',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:220,
                                mode:'local',
                                valueField:'doc_id',
                                displayField:'descripcion',
                                triggerAction:'all',
                                forceSelection:true,
								allowBlank:false,
                				editable:false,
                                listeners:
                                {
                                    select:function(cmb,record,index)
                                    {				
										/*
										Ext.Ajax.request({
											url:'tablas/numeracion-obtener-codigo',
											params:
											{
												doc_id:record.get('doc_id'),
												tipo:'2'
											},
											success:function(response,options)
											{        
												var res = Ext.decode(response.responseText);
												if(res.success){
													var numero=(Math.pow(10,res.data[0]['lon'])).toString()+(Number(res.data[0]['nro'])+1);
													var codigo=numero.substr(numero.length-res.data[0]['lon'],res.data[0]['lon'])
													Ext.getCmp(compras.id+'-numero').setValue(res.data[0]['serie']+ '-' + codigo);
												}else{
													Ext.getCmp(compras.id+'-numero').setValue('');
												}
												
											}
										});*/
										
										if(record.get('doc_id')==1){
											Ext.getCmp(compras.id+'-afecta_almacen').setVisible(false);
											Ext.getCmp(compras.id+'-afecta_almacen').setValue(false);
										}else{
											Ext.getCmp(compras.id+'-afecta_almacen').setVisible(true);
											Ext.getCmp(compras.id+'-afecta_almacen').setValue(true);
										}										
                                    }
                                }
                            } 
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:.28,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:compras.id+'-numero',
                                fieldLabel:'Número',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:120,
								allowBlank:false,
								listeners : {
									blur:function(obj){
										vDoc = obj.getValue();
										n=vDoc.indexOf("-");
										
										vSer = vDoc.substr(0,n);
										vSer=(Math.pow(10,3)).toString()+(Number(vSer));
										vSer=vSer.substr(vSer.length-3,3);
										
										vNro = vDoc.substr(n+1,vDoc.length - n);
										var vNro=(Math.pow(10,7)).toString()+(Number(vNro));
										var vNro=vNro.substr(vNro.length-7,7);
										Ext.getCmp(compras.id+'-numero').setValue(vSer+ '-' + vNro);
									}	
								}
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:70,layout:'form',
                        border:false,columnWidth:.3,
                        items:
                        [
                            {
                                xtype:'datefield',
                                id:compras.id+'-fecha',
                                emptyText:'Fecha',
                                width:100,
                                fieldLabel:'Fecha',
                                format:'d/m/Y',
                                altFormats : "d/m/Y",
                                value:'<? echo date('d/m/Y');?>',
                                style:'margin-left:7px'
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:compras.id+'-guia_remision',
                                fieldLabel:'Guía',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:120,
								listeners : {
									blur:function(obj){
										vDoc = obj.getValue();
										n=vDoc.indexOf("-");
										
										vSer = vDoc.substr(0,n);
										vSer=(Math.pow(10,3)).toString()+(Number(vSer));
										vSer=vSer.substr(vSer.length-3,3);
										
										vNro = vDoc.substr(n+1,vDoc.length - n);
										var vNro=(Math.pow(10,7)).toString()+(Number(vNro));
										var vNro=vNro.substr(vNro.length-7,7);
										Ext.getCmp(compras.id+'-guia_remision').setValue(vSer+ '-' + vNro);
									}	
								}
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:.42,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_condiciones_pago_lista,
                                id:compras.id+'-cpa_id',
                                fieldLabel:'Forma de Pago',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:150,
                                mode:'local',
                                valueField:'cpa_id',
                                displayField:'descripcion',
                                triggerAction:'all',
                                forceSelection:true,
								allowBlank:false,
								value:'1',
                				editable:false,
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:50,layout:'form',
                        border:false,columnWidth:.30,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_monedas_lista,
                                id:compras.id+'-mon_id',
                                fieldLabel:'Moneda',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:120,
                                mode:'local',
                                valueField:'mon_id',
                                displayField:'nombre',
                                triggerAction:'all',
                                forceSelection:true,
								allowBlank:false,
								value:'<?=$sesion->se_moneda_almacen?>',
                				editable:false,
								listeners:
                                {
                                    select:function(cmb,record,index)
                                    {
										if(cmb.getValue()=='1'){											
											document.getElementById(Ext.getCmp(compras.id+'-valor_bruto').label.id).innerHTML = 'Valor Bruto';
											document.getElementById(Ext.getCmp(compras.id+'-valor_descuento').label.id).innerHTML = 'Descuento';
											document.getElementById(Ext.getCmp(compras.id+'-valor_compra').label.id).innerHTML = 'Valor Compra';
											document.getElementById(Ext.getCmp(compras.id+'-impuesto_igv').label.id).innerHTML = 'Imp. IGV';
											document.getElementById(Ext.getCmp(compras.id+'-total_compra').label.id).innerHTML = 'Total Compra';
											
										}else{
											document.getElementById(Ext.getCmp(compras.id+'-valor_bruto').label.id).innerHTML = 'Valor Bruto';
											document.getElementById(Ext.getCmp(compras.id+'-valor_descuento').label.id).innerHTML = 'Descuento';
											document.getElementById(Ext.getCmp(compras.id+'-valor_compra').label.id).innerHTML = 'Valor Compra';
											document.getElementById(Ext.getCmp(compras.id+'-impuesto_igv').label.id).innerHTML = 'Imp. IGV';
											document.getElementById(Ext.getCmp(compras.id+'-total_compra').label.id).innerHTML = 'Total Compra';
										}										
                                    }
                                }
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:90,layout:'form',
                        border:false,columnWidth:.28,
                        items:
                        [        
                            {
                                xtype:'textfield',
                                id:compras.id+'-tipocambio',
                                fieldLabel:'Tipo de Cambio',
                                itemCls: 'label01',
                                style:{marginLeft:'0px',textAlign:'right'},
                                width:70,
                                readOnly:true,
								value:vgTcC,
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:70,layout:'form',
                        border:false,columnWidth:.3,
                        items:
                        [
                            /*{
                                xtype:'datefield',
                                id:compras.id+'-fecha_vencimiento',
                                emptyText:'Vencimiento',
                                width:100,
                                fieldLabel:'Vencimiento',
                                format:'d/m/Y',
                                altFormats : "d-m-Y",
                                readOnly:true,
                                style:'margin-left:7px'
                            }*/
                        ]
                    }
                    ,
                    {
                        xtype:'panel',labelWidth:105,layout:'form',
                        border:false,columnWidth:.20,
                        items:
                        [
                            {
                                xtype:'checkbox',
                                id:compras.id+'-afecta_almacen',
                                fieldLabel:'Afecta Almacén',
                                checked:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:85,layout:'form',
                        border:false,columnWidth:.20,
                        items:
                        [        
                            {
                                xtype:'checkbox',
                                id:compras.id+'-inc_igv',
                                fieldLabel:'Incluye IGV',
                                checked:true,
								enableKeyEvents: true,
								listeners:{
									check:function(obj, even){
										compras.calcular();
									}
								}
                            }
                        ]
                    },
                    {
                        xtype:'panel',layout:'form',
                        border:true,columnWidth:1,height:150,/*autoScroll:true,*/
                        bodyStyle:'margin-bottom:7px',
                        items:
                        [        
                            grid_guiasAsignadas
                        ]
                    }					
                    ,
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:.2,
                        items:
                        [        
                            {
                                xtype:'textfield',
                                id:compras.id+'-valor_bruto',
                                fieldLabel:'Valor Bruto',
                                itemCls: 'label01',
                                style:{marginLeft:'0px',textAlign:'right'},
                                width:70,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:.18,
                        items:
                        [        
                            {
                                xtype:'textfield',
                                id:compras.id+'-valor_descuento',
                                fieldLabel:'Descuento',
                                itemCls: 'label01',
                                style:{marginLeft:'0px',textAlign:'right'},
                                width:60,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:90,layout:'form',
                        border:false,columnWidth:.22,
                        items:
                        [        
                            {
                                xtype:'textfield',
                                id:compras.id+'-valor_compra',
                                fieldLabel:'Valor Compra',
                                itemCls: 'label01',
                                style:{marginLeft:'0px',textAlign:'right'},
                                width:70,
                                readOnly:true
                            }
                        ]
                    }
                    ,
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:.18,
                        items:
                        [        
                            {
                                xtype:'textfield',
                                id:compras.id+'-impuesto_igv',
                                fieldLabel:'Imp. IGV',
                                itemCls: 'label01',
                                style:{marginLeft:'0px',textAlign:'right'},
                                width:70,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:90,layout:'form',
                        border:false,columnWidth:.22,
                        items:
                        [        
                            {
                                xtype:'textfield',
                                id:compras.id+'-total_compra',
                                fieldLabel:'Total Compra',
                                itemCls: 'label01',
                                style:{marginLeft:'0px',textAlign:'right'},
                                width:70,
                                readOnly:true
                            }
                        ]
                    }
					,
                    {
                        xtype:'panel',labelWidth:80,layout:'form',
                        border:false,columnWidth:0.6,
                        items:
                        [        
                            {
                                xtype:'textarea',
                                id:compras.id+'-observacion',
                                fieldLabel:'Observacion',
                                itemCls: 'label01',
                                style:{marginLeft:'7px',textAlign:'left'},
                                width:300,
								height:40
                            }
                        ]
                    }
					,
                    {
                        xtype:'label',
						id:compras.id+'-msganulado',
                        columnWidth:0.4,
						text:'DOCUMENTO ANULADO',
						style:{color:'#ff0000',fontSize:'20px'}
                    }
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_nuevo,'-',btn_guardar,btn_actualizar,btn_editar,'-',btn_anular,btn_eliminar,'-',btn_imprimir,btn_cancelar,
							{
								xtype:'datefield',
								id:compras.id+'-fec_ini',
								width:100,
								format:'d/m/Y',
								emptyText:'Inicio',
								altFormats : "d/m/Y",
								value:'<? echo $fecha_atras;?>',
								style:'margin-left:7px',
								listeners:{
									select:function(obj){
										store_compras_lista.load({params:{fec_ini:obj.getValue(), fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});
									}	
								}
							},{
								xtype:'datefield',
								id:compras.id+'-fec_fin',
								width:100,
								emptyText:'Fin',
								format:'d/m/Y',
								altFormats : "d/m/Y",
								value:'<? echo date('d/m/Y');?>',
								style:'margin-left:7px',
								listeners:{
									select:function(obj){
										store_compras_lista.load({params:{fec_fin:obj.getValue(), fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});
									}	
								}
							},
							{
								xtype:'combo',
								store:store_documentos_lista,
								id:compras.id+'-doc_id_buscar',
								fieldLabel:'Documento',
								itemCls: 'label01',
								style:'margin-left:7px',
								width:110,
								mode:'local',
								valueField:'doc_id',
								displayField:'descripcion',
								triggerAction:'all',
								forceSelection:true,
								emptyText:'Doc',
								editable:false,
								listeners:
								{
									select:function(cmb,record,index)
									{				
											store_compras_lista.load({params:{fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(), fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(),doc_id:cmb.getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});									
									}
								}
							} ,
							{
                                xtype:'textfield',
                                id:compras.id+'-numero_buscar',
                                fieldLabel:'',
                                itemCls: 'label01',
                                style:'margin-left:7px;padding-right:7px',
								emptyText:'Nro de Doc. Compra o Proveedor',
                                width:200,
								listeners : {
									specialkey:function(obj,e){
										if(e.getKey() == 13)
		                                {
										store_compras_lista.load({params:{fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(), fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(), nro_doc:obj.getValue(),start:0,limit:100}});
										}
									}	
								}
                            }                   
                        ]
                    }],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'fit',
                xtype: 'panel',
                width:'99%',
                autoScroll: true,  
                border:false,
                items:
                [
                    grid_compras_lista
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
            ,
            {  
                id:compras.id+'-panel_derecho',
                region: 'east',
                xtype: 'panel',
                collapsible:true,
                layout: 'form',
                split:true,
                collapsed:true,
                width:'100%',
                border:false,
                items:
                [
                    panel_form
                ]  
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_compras',
                                        title:'compras', 
                                        width: 1024,
                                        height:600,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
                                        collapsible:false,
                                        draggable:true,
                        onEsc:function(){Ext.getCmp('win_compras').close();}, resizable:true,
                        items:panel,
                        buttonAlign:'center'
            });
            
            Ext.getCmp('win_compras').show();
            Ext.getCmp('win_compras').center();
            Ext.getCmp('win_compras').toFront();
			
			
			
            compras.fn_habilitar(false,0);
			
			
			/*Ext.getCmp(compras.id+'-grid_lista').store.load({params:{fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(), fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});*/
			
            Ext.getCmp(compras.id+'-panel_derecho').collapse();
			Ext.getCmp(compras.id+'-panel_derecho').setVisible(false);
            
            
                
            
        },
        fn_nuevo:function()
        {
			Ext.Msg.wait('Generando código de Compra... por favor espere!');
            Ext.Ajax.request({
				url:'movimientos/compras-codigo',
				params:
				{
					table:'movimientos_compras'
				},
				success:function(response,options)
				{   
					Ext.Msg.hide();
					var res = Ext.decode(response.responseText);						
					var numero="000000000"+res.codigo;
					var agencia= "000"+vgIdTienda;
					var codigo="CO"+agencia.substr(agencia.length-3,3)+numero.substr(numero.length-9,9)
					Ext.getCmp(compras.id+'-codigo').setValue(codigo);
				}
			});           
            
			Ext.getCmp(compras.id+'-tipo_ingreso').setValue('1');
			Ext.getCmp(compras.id+'-prv_id').setValue('');
			Ext.getCmp(compras.id+'-prv_ruc').setValue('');
			Ext.getCmp(compras.id+'-prv_codigo').setValue('');
			Ext.getCmp(compras.id+'-doc_id').setValue('');
			Ext.getCmp(compras.id+'-numero').setValue('');
			Ext.getCmp(compras.id+'-guia_remision').setValue('');
			Ext.getCmp(compras.id+'-cpa_id').setValue('1');
			Ext.getCmp(compras.id+'-mon_id').setValue('1');
			Ext.getCmp(compras.id+'-afecta_almacen').setValue(true);
			Ext.getCmp(compras.id+'-inc_igv').setValue(true);
			Ext.getCmp(compras.id+'-msganulado').setVisible(false);
			Ext.getCmp(compras.id+'-observacion').setValue('');
			
			compras.fn_habilitar(true,1);
			Ext.getCmp(compras.id+'-guias_asignadas').store.removeAll(false);
        },
        fn_editar:function()
        {
            var rs=Ext.getCmp(compras.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {				
				Ext.getCmp(compras.id+'-panel_derecho').expand();
				Ext.getCmp(compras.id+'-panel_derecho').setVisible(true);
				Ext.getCmp(compras.id+'-msganulado').setVisible(false);
                compras.fn_habilitar(true,2);
				if(rs.get('anulado')=='1'){
					Ext.getCmp(compras.id+'-btn_actualizar').setVisible(false);
					Ext.getCmp(compras.id+'-msganulado').setVisible(true);
				}
				
				Ext.getCmp(compras.id+'-mco_id').setValue(rs.get('mco_id'));
				var numero="000000000"+rs.get('codigo');
				var agencia= "000"+vgIdTienda;
				var codigo="CO"+agencia.substr(agencia.length-3,3)+numero.substr(numero.length-9,9)
				Ext.getCmp(compras.id+'-codigo').setValue(codigo);
				
				Ext.getCmp(compras.id+'-tipo_ingreso').setValue(rs.get('tipo_ingreso'));
				Ext.getCmp(compras.id+'-fecha').setValue(rs.get('fec_ven'));
				
				Ext.getCmp(compras.id+'-prv_id').store.load({params:{campo:'prv_id',query:rs.get('prv_id'),start:0,limit:1}});
				Ext.getCmp(compras.id+'-prv_id').setValue(rs.get('prv_id'));
				Ext.getCmp(compras.id+'-prv_id').setRawValue(rs.get('nombre_proveedor'));
				
				Ext.getCmp(compras.id+'-prv_ruc').setValue(rs.get('ruc'));
				Ext.getCmp(compras.id+'-prv_codigo').setValue(rs.get('prv_codigo'));
				Ext.getCmp(compras.id+'-doc_id').setValue(rs.get('doc_id'));
				Ext.getCmp(compras.id+'-numero').setValue(rs.get('doc_n'));
				Ext.getCmp(compras.id+'-guia_remision').setValue(rs.get('n_guia'));
				Ext.getCmp(compras.id+'-cpa_id').setValue(rs.get('cpa_id'));
				Ext.getCmp(compras.id+'-mon_id').setValue(rs.get('mon_id'));
				Ext.getCmp(compras.id+'-observacion').setValue(rs.get('observacion'));
				
				if(rs.get('afecta')=='S'){
					Ext.getCmp(compras.id+'-afecta_almacen').setValue(true);
				}else{
					Ext.getCmp(compras.id+'-afecta_almacen').setValue(false);
				}
				if(rs.get('formato')=='S'){
					Ext.getCmp(compras.id+'-inc_igv').setValue(true);
				}else{
					Ext.getCmp(compras.id+'-inc_igv').setValue(false);	
				}
				Ext.Msg.wait('Cargando detalle de compra... por favor espere!');
				Ext.Ajax.request({
					url:'movimientos/compras-detalle',
					params:
					{
						mco_id:rs.get('mco_id')
					},
					success:function(response,options)
					{     
						Ext.Msg.hide();        
						//alert(response.responseText);
						var res = Ext.decode(response.responseText);
						Ext.getCmp(compras.id+'-guias_asignadas').store.removeAll(false);						
						for (i=0;i<res.data.length;i++){
							//alert(res.data[i]);
							detalle = res.data[i];
							var u = new compras.store_reader.recordType({
								id:detalle['pro_id'],cantidad:detalle['cantidad'],codigo:detalle['codigo1'],detalle:detalle['producto'],precio:detalle['precio_compra'],descuento:detalle['descuento'],total:detalle['total'],ume_id:detalle['ume_id'], marca:detalle['marca']
							});
							//alert(detalle['pro_id']);
							Ext.getCmp(compras.id+'-guias_asignadas').stopEditing();
							compras.store_reader.insert(compras.store_reader.getCount(), u);
							Ext.getCmp(compras.id+'-guias_asignadas').startEditing(compras.store_reader.getCount()-1,1);
						}		
						//alert("salir");			
						compras.calcular();			
					}
				});
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
        fn_actualizar:function()
        {
			if(compras.fn_validar()){
				if(Ext.getCmp(compras.id+'-afecta_almacen').getValue()){
					vAfecta = 'S';	
				}else{
					vAfecta = 'N';	
				}
				if(Ext.getCmp(compras.id+'-inc_igv').getValue()){
					vFormato = 'S';	
				}else{
					vFormato = 'N';	
				}
				var vData= new Array();
				var v_detalle= new Array();
				for(i=0;i<Ext.getCmp(compras.id+'-guias_asignadas').store.getCount();i++)
				{
					datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(i);
					vValore = datos.get('id') + '.@.' + datos.get('cantidad') + '.@.' + datos.get('codigo') + '.@.' + datos.get('detalle') + '.@.' + datos.get('precio') + '.@.' + datos.get('descuento') + '.@.' + datos.get('total') + '.@.' + datos.get('ume_id') + '.@.' + vAfecta + '.@.' + datos.get('valor_bruto') + '.@.' + datos.get('valor_desc');
					vData[i] = vValore;
				}

				Ext.getCmp(compras.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'movimientos/compras-actualizar',
					params:{ 
						mco_id:Ext.getCmp(compras.id+'-mco_id').getValue(),
						codigo:Ext.getCmp(compras.id+'-codigo').getValue(),
						prv_id:Ext.getCmp(compras.id+'-prv_id').getValue(),
						tipo_ingreso:Ext.getCmp(compras.id+'-tipo_ingreso').getValue().getGroupValue(),
						doc_id:Ext.getCmp(compras.id+'-doc_id').getValue(),
						doc_n:Ext.getCmp(compras.id+'-numero').getValue(),
						n_guia:Ext.getCmp(compras.id+'-guia_remision').getValue(),
						cpa_id:Ext.getCmp(compras.id+'-cpa_id').getValue(),
						mon_id:Ext.getCmp(compras.id+'-mon_id').getValue(),
						valor_compra:Ext.getCmp(compras.id+'-valor_compra').getValue(),
						valor_bruto:Ext.getCmp(compras.id+'-valor_bruto').getValue(),
						valor_desc:Ext.getCmp(compras.id+'-valor_descuento').getValue(),
						impuesto_igv:Ext.getCmp(compras.id+'-impuesto_igv').getValue(),
						total_compra:Ext.getCmp(compras.id+'-total_compra').getValue(),
						fecha:Ext.getCmp(compras.id+'-fecha').getValue(),
						tip_doc:Ext.getCmp(compras.id+'-doc_id').getRawValue(),
						observacion:Ext.getCmp(compras.id+'-observacion').getValue(),
						afecta_stock:vAfecta,
						formato:vFormato,
						igv:18,
						"v_detalle[]":vData,
					},
					waitTitle: 'Actualizando Informacion',
					waitMsg: 'Enviando datos..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(compras.id+'-panel_derecho').collapse();
							Ext.getCmp(compras.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							compras.fn_habilitar(false,0);
							Ext.getCmp(compras.id+'-grid_lista').store.load({params:{fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(), fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(compras.id+res.campo).focus(true,10);							
						}
						Ext.getCmp(compras.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(compras.id+res.campo).focus(true,10);							
					}
				});				
				/*Ext.Ajax.request({
					url:'movimientos/compras-guardar',
					params:
					{
						mve_id:Ext.getCmp(ventas.id+'-mve_id').getValue(),
						codigo:Ext.getCmp(compras.id+'-codigo').getValue(),
						prv_id:Ext.getCmp(compras.id+'-prv_id').getValue(),
						tipo_ingreso:Ext.getCmp(compras.id+'-tipo_ingreso').getValue().getGroupValue(),
						doc_id:Ext.getCmp(compras.id+'-doc_id').getValue(),
						doc_n:Ext.getCmp(compras.id+'-numero').getValue(),
						n_guia:Ext.getCmp(compras.id+'-guia_remision').getValue(),
						cpa_id:Ext.getCmp(compras.id+'-cpa_id').getValue(),
						mon_id:Ext.getCmp(compras.id+'-mon_id').getValue(),
						valor_compra:Ext.getCmp(compras.id+'-valor_compra').getValue(),
						impuesto_igv:Ext.getCmp(compras.id+'-impuesto_igv').getValue(),
						total_compra:Ext.getCmp(compras.id+'-total_compra').getValue(),
						fecha:Ext.getCmp(compras.id+'-fecha').getValue(),
						tip_doc:Ext.getCmp(compras.id+'-doc_id').getRawValue(),
						afecta_stock:vAfecta,
						"v_detalle[]":vData,
					},
					success:function(response,options)
					{
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(compras.id+'-panel_derecho').collapse();
							Ext.getCmp(compras.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							compras.fn_habilitar(false,0);
							Ext.getCmp(compras.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(compras.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
        fn_guardar:function()
        {	
			if(compras.fn_validar()){
				if(Ext.getCmp(compras.id+'-afecta_almacen').getValue()){
					vAfecta = 'S';	
				}else{
					vAfecta = 'N';	
				}
				if(Ext.getCmp(compras.id+'-inc_igv').getValue()){
					vFormato = 'S';	
				}else{
					vFormato = 'N';	
				}
				var vData= new Array();
				var v_detalle= new Array();
				for(i=0;i<Ext.getCmp(compras.id+'-guias_asignadas').store.getCount();i++)
				{
					datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(i);
					vValore = datos.get('id') + '.@.' + datos.get('cantidad') + '.@.' + datos.get('codigo') + '.@.' + datos.get('detalle') + '.@.' + datos.get('precio') + '.@.' + datos.get('descuento') + '.@.' + datos.get('total') + '.@.' + datos.get('ume_id') + '.@.' + vAfecta + '.@.' + datos.get('valor_bruto') + '.@.' + datos.get('valor_desc');
					vData[i] = vValore;
				}
				//alert("Antes");
				Ext.getCmp(compras.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'movimientos/compras-guardar',
					params:{ 
						codigo:Ext.getCmp(compras.id+'-codigo').getValue(),
						prv_id:Ext.getCmp(compras.id+'-prv_id').getValue(),
						tipo_ingreso:Ext.getCmp(compras.id+'-tipo_ingreso').getValue().getGroupValue(),
						doc_id:Ext.getCmp(compras.id+'-doc_id').getValue(),
						doc_n:Ext.getCmp(compras.id+'-numero').getValue(),
						n_guia:Ext.getCmp(compras.id+'-guia_remision').getValue(),
						cpa_id:Ext.getCmp(compras.id+'-cpa_id').getValue(),
						mon_id:Ext.getCmp(compras.id+'-mon_id').getValue(),
						valor_compra:Ext.getCmp(compras.id+'-valor_compra').getValue(),
						valor_bruto:Ext.getCmp(compras.id+'-valor_bruto').getValue(),
						valor_desc:Ext.getCmp(compras.id+'-valor_descuento').getValue(),
						impuesto_igv:Ext.getCmp(compras.id+'-impuesto_igv').getValue(),
						total_compra:Ext.getCmp(compras.id+'-total_compra').getValue(),
						fecha:Ext.getCmp(compras.id+'-fecha').getValue(),
						tip_doc:Ext.getCmp(compras.id+'-doc_id').getRawValue(),
						observacion:Ext.getCmp(compras.id+'-observacion').getValue(),
						afecta_stock:vAfecta,
						formato:vFormato,
						igv:18,
						"v_detalle[]":vData,
					},
					waitTitle: 'Guardando Informacion',
					waitMsg: 'Enviando datos..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(compras.id+'-panel_derecho').collapse();
							Ext.getCmp(compras.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							compras.fn_habilitar(false,0);
							Ext.getCmp(compras.id+'-grid_lista').store.load({params:{fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(), fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(compras.id+res.campo).focus(true,10);							
						}
						Ext.getCmp(compras.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(compras.id+res.campo).focus(true,10);							
					}
				});				

				/*Ext.Ajax.request({
					url:'movimientos/compras-guardar',
					params:
					{
						codigo:Ext.getCmp(compras.id+'-codigo').getValue(),
						prv_id:Ext.getCmp(compras.id+'-prv_id').getValue(),
						tipo_ingreso:Ext.getCmp(compras.id+'-tipo_ingreso').getValue().getGroupValue(),
						doc_id:Ext.getCmp(compras.id+'-doc_id').getValue(),
						doc_n:Ext.getCmp(compras.id+'-numero').getValue(),
						n_guia:Ext.getCmp(compras.id+'-guia_remision').getValue(),
						cpa_id:Ext.getCmp(compras.id+'-cpa_id').getValue(),
						mon_id:Ext.getCmp(compras.id+'-mon_id').getValue(),
						valor_compra:Ext.getCmp(compras.id+'-valor_compra').getValue(),
						impuesto_igv:Ext.getCmp(compras.id+'-impuesto_igv').getValue(),
						total_compra:Ext.getCmp(compras.id+'-total_compra').getValue(),
						fecha:Ext.getCmp(compras.id+'-fecha').getValue(),
						tip_doc:Ext.getCmp(compras.id+'-doc_id').getRawValue(),
						afecta_stock:vAfecta,
						formato:vFormato,
						igv:18,
						"v_detalle[]":vData,
					},
					success:function(response,options)
					{
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(compras.id+'-panel_derecho').collapse();
							Ext.getCmp(compras.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							compras.fn_habilitar(false,0);
							Ext.getCmp(compras.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(compras.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
		fn_anular:function()
        {
            var rs=Ext.getCmp(compras.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				if(rs.get('anulado')=='1'){
					og.msg("Error","Documento ya esta anulado");
					return;
				}
				Ext.Msg.confirm('Alerta', 'Desea Anular?<br>Documento :<br>' + rs.get('doc_n'), function(btn) {
					if(btn == 'yes')
					{
						Ext.Msg.wait('Anulando compra... por favor espere!');
						Ext.Ajax.request({
							url:'movimientos/compras-anular',
							params:
							{
								mco_id:rs.get('mco_id')
							},
							success:function(response,options)
							{           
								Ext.Msg.hide();  
								var res = Ext.decode(response.responseText);
								if(res.success){
									og.msg("Ok","El registro se ha anulado");
									compras.fn_habilitar(false,0);
									Ext.getCmp(compras.id+'-grid_lista').store.load({params:{fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(), fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});
								}else{
									og.msg("Error",res.mensaje);
									Ext.getCmp(compras.id+res.campo).focus(true,10);				
								}
							}
						});
					}
				 });
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
        fn_eliminar:function()
        {
            var rs=Ext.getCmp(compras.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.Msg.confirm('Alerta', 'Desea eliminar?<br>Documento :<br>' + rs.get('doc_n'), function(btn) {
					if(btn == 'yes')
					{
						Ext.Msg.wait('Eliminando compra... por favor espere!');
						Ext.Ajax.request({
							url:'movimientos/compras-eliminar',
							params:
							{
								mco_id:rs.get('mco_id')
							},
							success:function(response,options)
							{             			
								Ext.Msg.hide();
								var res = Ext.decode(response.responseText);
								if(res.success){
									og.msg("Ok","El registro se ha eliminado");
									compras.fn_habilitar(false,0);
									Ext.getCmp(compras.id+'-grid_lista').store.load({params:{fec_ini:Ext.getCmp(compras.id+'-fec_ini').getValue(), fec_fin:Ext.getCmp(compras.id+'-fec_fin').getValue(),doc_id:Ext.getCmp(compras.id+'-doc_id_buscar').getValue(),nro_doc:Ext.getCmp(compras.id+'-numero_buscar').getValue(),start:0,limit:100}});
								}else{
									og.msg("Error",res.mensaje);
									Ext.getCmp(compras.id+res.campo).focus(true,10);				
								}
							}
						});
					}
				 });
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },		
        calcular:function()
        {
            var valor_compra='0';
			var valor_bruto='0';
            var impuesto_igv='0';
            var total_compra='0';
			var valor_desc ='0';
            var datos='';
            for(i=0;i<Ext.getCmp(compras.id+'-guias_asignadas').store.getCount();i++)
            {
                datos=Ext.getCmp(compras.id+'-guias_asignadas').getStore(0).getAt(i);
				//alert(datos.get('ind_cal'));
				if(datos.get('ind_cal')==2){
					vValor = Number(datos.get('total')) / Number(datos.get('cantidad'));													
					vDesc = datos.get('descuento');
					var n=vDesc.split("+");
					if(n==0){
						vValor = (100 * vValor) / ( 100 - Number(vDesc));
						vValor = Math.round(vValor*100)/100;	
						vDesc = Number(vDesc);
					}else{
						for(j=n.length - 1;j>=0;j--){
							vValor =(100 * vValor) / ( 100 - Number(n[j]));
							vValor = Math.round(vValor*100)/100;	
						}
					}
					datos.set('precio',vValor);
					if(vDesc==0){
						datos.set('valor_desc',0);
						datos.set('valor_bruto',Number(datos.get('total')));
					}else{
						//alert(vValor);
						datos.set('valor_bruto',vValor * Number(datos.get('cantidad')));
						datos.set('valor_desc',vValor * Number(datos.get('cantidad')) - Number(datos.get('total')));
					}
					
					
				}else{
					vValor = Number(datos.get('cantidad')) * Number(datos.get('precio'));
					vBruto = vValor;
					vBruto = Math.round(vBruto*100)/100;	
					datos.set('valor_bruto',vBruto);
					
					vDesc = datos.get('descuento');
					var n=vDesc.split("+");
					if(n==0){
						vDesc = Number(vDesc);
						vValor = vValor - (vValor*Number(vDesc))/100;
						vValor = Math.round(vValor*100)/100;	
					}else{
						vDesc=1;
						for(j=0;j<n.length;j++){
							vValor = vValor - (vValor*Number(n[j]))/100;
							vValor = Math.round(vValor*100)/100;	
						}
					}
					/*vValor = vValor - (vValor*Number(datos.get('descuento')))/100;
					vValor = Math.round(vValor*100)/100;*/
					if(vDesc==0){
						datos.set('valor_desc',0);
					}else{
						datos.set('valor_desc',vBruto - vValor);
					}
					datos.set('total',$.number(vValor, 2, '.', ''));
				}
				
				
				//datos.beginEdit( );
				//datos.set('detalle','Cambio de DATOS');
				datos.set('itemid',i+1);
                                valor_compra=Number(valor_compra)+Number(datos.get('total'));
				valor_desc = Number(valor_desc)+Number(datos.get('valor_desc'));
				valor_bruto = Number(valor_bruto)+Number(datos.get('valor_bruto'));
            }
			
			valor_compra= Math.round(valor_compra*100)/100;
			if(Ext.getCmp(compras.id+'-inc_igv').getValue()){
				Ext.getCmp(compras.id+'-total_compra').setValue($.number(valor_compra, 2, '.', ''));
				
				impuesto_igv= (valor_compra * 18)  / 118 ;
				impuesto_igv = Math.round(impuesto_igv*100 ) / 100;
				valor_compra=(valor_compra-impuesto_igv);
				
				Ext.getCmp(compras.id+'-impuesto_igv').setValue($.number(impuesto_igv, 2, '.', ''));
				valor_compra = Math.round(valor_compra*100)/100;
				Ext.getCmp(compras.id+'-valor_compra').setValue($.number(valor_compra, 2, '.', ''));
			}else{
				valor_compra = Math.round(valor_compra*100)/100;
				Ext.getCmp(compras.id+'-valor_compra').setValue($.number(valor_compra, 2, '.', ''));
				impuesto_igv=Math.round(((valor_compra * 18)/100)*100)/100 ;
				total_compra=(Number(Math.round(valor_compra*100)/100)+Number(impuesto_igv));
				Ext.getCmp(compras.id+'-impuesto_igv').setValue($.number(impuesto_igv, 2, '.', ''));
				Ext.getCmp(compras.id+'-total_compra').setValue($.number(total_compra, 2, '.', ''));
			}			
			valor_desc = Math.round(valor_desc*100)/100;
			Ext.getCmp(compras.id+'-valor_descuento').setValue($.number(valor_desc, 2, '.', ''));
			valor_bruto = Math.round(valor_bruto*100)/100;	
			Ext.getCmp(compras.id+'-valor_bruto').setValue($.number(valor_bruto, 2, '.', ''));
        },
		fn_validar:function(){
			if(!Ext.getCmp(compras.id+'-prv_id').isValid())
            {
                og.msg("Error", "Ingrese el Proveedor");
                Ext.getCmp(compras.id+'-prv_id').focus(true,10);
                return false;
            }
			if(!Ext.getCmp(compras.id+'-doc_id').isValid())
            {
                og.msg("Error", "Ingrese el Documento");
                Ext.getCmp(compras.id+'-doc_id').focus(true,10);
                return false;
            }
			if(!Ext.getCmp(compras.id+'-numero').isValid())
            {
                og.msg("Error", "Ingrese el Número del Documento");
                Ext.getCmp(compras.id+'-numero').focus(true,10);
                return false;
            }
			if(!Ext.getCmp(compras.id+'-cpa_id').isValid())
            {
                og.msg("Error", "Ingrese la Condición de Pago");
                Ext.getCmp(compras.id+'-cpa_id').focus(true,10);
                return false;
            }
			if(!Ext.getCmp(compras.id+'-mon_id').isValid())
            {
                og.msg("Error", "Ingrese la Moneda de Pago");
                Ext.getCmp(compras.id+'-mon_id').focus(true,10);
                return false;
            }
			if(Ext.getCmp(compras.id+'-guias_asignadas').store.getCount()==0){
				og.msg("Error", "Por favor ingrese detalle del Documento");
                Ext.getCmp(compras.id+'-mon_id').focus(true,10);
                return false;
			}
			return true;
		},
		fn_habilitar:function(sw, tipo)
        {
			if(!sw){
				Ext.getCmp(compras.id+'-btn_guardar').setVisible(sw);
				Ext.getCmp(compras.id+'-btn_actualizar').setVisible(sw);
			}else{
				if(tipo==1){
					Ext.getCmp(compras.id+'-btn_guardar').setVisible(sw);
					Ext.getCmp(compras.id+'-btn_actualizar').setVisible(!sw);
				}else{
					Ext.getCmp(compras.id+'-btn_guardar').setVisible(!sw);
					Ext.getCmp(compras.id+'-btn_actualizar').setVisible(sw);
				}
			}
			Ext.getCmp(compras.id+'-btn_nuevo').setVisible(!sw);			
			Ext.getCmp(compras.id+'-btn_cancelar').setVisible(sw);
			
			Ext.getCmp(compras.id+'-btn_editar').setVisible(!sw);
			Ext.getCmp(compras.id+'-btn_eliminar').setVisible(!sw);
			Ext.getCmp(compras.id+'-btn_anular').setVisible(!sw);

			Ext.getCmp(compras.id+'-btn_editar').disable();
			Ext.getCmp(compras.id+'-btn_eliminar').disable();
			Ext.getCmp(compras.id+'-btn_anular').disable();
			
			//Ext.getCmp(compras.id+'-buscar').setVisible(!sw);			
			//Ext.getCmp(compras.id+'-combo_describe').setVisible(!sw);
			
			Ext.getCmp(compras.id+'-fec_ini').setVisible(!sw);	
			Ext.getCmp(compras.id+'-fec_fin').setVisible(!sw);	
			Ext.getCmp(compras.id+'-doc_id_buscar').setVisible(!sw);	
			Ext.getCmp(compras.id+'-numero_buscar').setVisible(!sw);	
			
			Ext.getCmp(compras.id+'-btn_imprimir').setVisible(!sw);			
        },
		fn_buscar_producto:function(){
			var btn_cerrar=new Ext.Button({
                id:compras.id+'-btn_cerrar',
                text:'Cerrar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp('win_buscar_mercaderias_compras').close();
                        }
                    }
            });
            
            var store_mercaderias_lista_stock=new Ext.data.JsonStore({
                url:'maestros/mercaderias-lista',
                root:'data',
                totalProperty:'total',
                fields:['mcd_id','codigo1','codigo2','codigo3','nombre','ume_id','mar_id','lin_id','precio_costo','precio_venta','stock_minimo','stock_actual', 'utilidad', 'desc1', 'desc2', 'desc3', 'desc4','activo', 'fam_id', 'ume_nom', 'precio_compra', 'ind_calculo','mar_nom', 'stock_pro'],
				remoteSort:true,
				sortInfo: {field:'nombre', direction:'asc'}
            });

            var store_mercaderias_describe=new Ext.data.JsonStore({
                url:'maestros/mercaderias-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });
            
            store_mercaderias_describe.load({params:{table:'maestros_mercaderias'}});
            
			var store_lineasbusq_lista=new Ext.data.JsonStore({
                url:'tablas/lineas-lista',
                root:'data',
                totalProperty:'total',
                fields:['lin_id','nombre']
            });
			store_lineasbusq_lista.load();
			var combo_lineas_busq=new Ext.form.ComboBox({
                id:compras.id+'-combo_lineas_busq',
                store:store_lineasbusq_lista,
                valueField:'lin_id',
                displayField:'nombre',
                triggerAction:'all',
                emptyText:'Linea',
                mode:'local',
                width:200,
                editable:false,
				listeners:
					{
						select:function(cmb,record,index)
						{
							store_mercaderias_lista_stock.load({params:{lin_id:cmb.getValue(),campo:Ext.getCmp(compras.id+'-combo_describe_mercaderias').getValue(),query:Ext.getCmp(compras.id+'-buscar_mercaderia').getValue(),start:0,limit:100}});
						}
					}
            });
			
            var pagerStock = new Ext.PagingToolbar({
                id:compras.id+'_pager',
                store:store_mercaderias_lista_stock,
                displayInfo: true,
                displayMsg: '{0} - {1} de {2} Registros',
                emptyMsg: 'No existen registros',
                pageSize:100
            });
			
			pagerStock.on('beforechange',function(bar,params){  
				params.campo = Ext.getCmp(compras.id+'-combo_describe_mercaderias').getValue();
				params.query = Ext.getCmp(compras.id+'-buscar_mercaderia').getValue();
				params.lin_id = Ext.getCmp(compras.id+'-combo_lineas_busq').getValue();
			}); 
            
            var combo_mercaderias_describe=new Ext.form.ComboBox({
                id:compras.id+'-combo_describe_mercaderias',
                store:store_mercaderias_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
                mode:'local',
                width:100,
                editable:false
            });
            
            var grid_mercaderias_lista_stock = new Ext.grid.GridPanel({
                id:compras.id+'-grid_mercaderias_lista_stock',
                store: store_mercaderias_lista_stock,
                singleSelect:true,
                forceSelection:true,
                columnLines:true,
                width:'580',
                stateful: true,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                bbar:pagerStock,
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'mcd_id',width:25, hidden:true},
                    {header:'Código 1',sortable :true,dataIndex:'codigo1',width:100},
                    {header:'Código 2',sortable :true,dataIndex:'codigo2',width:100},
                    {header:'Código 3',sortable :true,dataIndex:'codigo3',width:100,hidden:true},
                    {header:'Descripción',sortable :true,dataIndex:'nombre',width:250},
                    {header:'Marca',sortable :true,dataIndex:'mar_nom',width:100},
					{header:'Unidad de Medida',sortable :true,dataIndex:'ume_nom',width:100,hidden:true},
					{header:'Stock',sortable :true,dataIndex:'stock_pro',width:75,align:'right'},
					<?php if($this->usp_id<>7){?>
                    {header:'P. Compra',sortable :true,dataIndex:'precio_compra',width:75,align:'right',hidden:true},
					{header:'P. Costo',sortable :true,dataIndex:'precio_costo',width:75,align:'right'},
					<?php }?>
                    {header:'P. Venta',sortable :true,dataIndex:'precio_venta',width:75,align:'right'},
					{header:'Tipo',sortable :true,dataIndex:'tipo_mcd',width:40,align:'left'},
                    {header:'Stock Mínimo',sortable :true,dataIndex:'stock_minimo',width:100,align:'right',hidden:true},
					{header:'% Incremento',sortable :true,dataIndex:'utilidad',width:100,align:'right',hidden:true},
					{header:'% Desc 1',sortable :true,dataIndex:'desc1',width:100,align:'right',hidden:true},
					{header:'% Desc 2',sortable :true,dataIndex:'desc2',width:100,align:'right',hidden:true},
					{header:'% Desc 3',sortable :true,dataIndex:'desc3',width:100,align:'right',hidden:true},
					{header:'% Desc 4',sortable :true,dataIndex:'desc4',width:100,align:'right',hidden:true},
                    {header:'Estado',sortable :true,dataIndex:'activo',width:100,hidden:true}
                    ],
                listeners:
                {
                    rowdblclick:function()
                    {
                        var rs=Ext.getCmp(compras.id+'-grid_mercaderias_lista_stock').getSelectionModel().getSelected();
						
						if(rs)
			            {
							Ext.getCmp('win_buscar_mercaderias_compras').close();
							var u = new compras.store_reader.recordType({
								id:rs.get('mcd_id'),cantidad:'',codigo:rs.get('codigo1'),detalle:rs.get('nombre'),marca:rs.get('mar_nom'),precio:rs.get('precio_venta'),descuento:'0',total:rs.get('precio_venta'),ume_id:rs.get('ume_id')
							});
							//alert("antes");
							Ext.getCmp(compras.id+'-guias_asignadas').stopEditing();
							compras.store_reader.insert(compras.store_reader.getCount(), u);
							Ext.getCmp(compras.id+'-guias_asignadas').startEditing(compras.store_reader.getCount()-1,1);
							//alert("despues");
							compras.calcular();
						}else{
							alert('No ha seleccionado ningun producto');
						}
                    }
                }
            });
            
            
            
            
            var panel2 = new Ext.Panel({  
            layout: 'border',

                                        tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            combo_lineas_busq, combo_mercaderias_describe,'-',
                    new Ext.app.SearchField({
                        id:compras.id+'-buscar_mercaderia', 
                        emptyText : 'Valor a buscar...',
                        enableKeyEvents: true,
                        store: store_mercaderias_lista_stock,
                        hasSearch : false,
                        width: 120,
                        listeners:
                        {
                            specialkey:function(obj, e)
                            {
                                if (e.getKey() == 13)
                                {
                                store_mercaderias_lista_stock.load({params:{lin_id:Ext.getCmp(compras.id+'-combo_lineas_busq').getValue(),campo:Ext.getCmp(compras.id+'-combo_describe_mercaderias').getValue(),query:Ext.getCmp(compras.id+'-buscar_mercaderia').getValue(),start:0,limit:100}});
                                }
                            }
                        }
                    }),'-',btn_cerrar
                    
                        ]
                    }],
            bodyStyle:'height:auto;width:650px;margin:auto;',
            border:false,
            items: [
            {  
				region: 'center',
				layout:'fit',
				xtype: 'panel',
				width:'640',
				autoScroll: true,  
				border:false,
				items:
				[
					grid_mercaderias_lista_stock
					
				]
			}
					
			  ]  
			});
            
             new Ext.Window({
				id:'win_buscar_mercaderias_compras',
				title:'Mercaderías',
				width: 800,
				height:450,
				layout:'fit',
				border:false,
				frame:true,
				autoDestroy:true,
				autoScroll:false,
				minimizable: false,
				modal:true,
				maximizable: false,
				closable:false,
				collapsible:false,
				draggable:true,
				onEsc:function(){Ext.getCmp('win_buscar_mercaderias_compras').close();},
				resizable:true,
				items:panel2,
				buttonAlign:'center',
				listeners: {
					'beforeclose': function(){ inicio.setActiveStyleSheet('gray'); }
				}
			});
			Ext.getCmp('win_buscar_mercaderias_compras').show();
			Ext.getCmp(compras.id+'-combo_describe_mercaderias').setValue('codigo1');
			inicio.setActiveStyleSheet('blue');
			//Ext.getCmp(compras.id+'-grid_mercaderias_lista_stock').store.load({params:{start:0,limit:100}});
		},
		fn_ubicaproveedor:function(vcampo, vvalor, vcodigo, vnombre, vruc){
			//alert('entra');
			Ext.getCmp(compras.id+'-prv_id').store.load({params:{campo:vcampo,query:vvalor,start:0,limit:100}});
			Ext.getCmp(compras.id+'-prv_id').setValue(vvalor);
			Ext.getCmp(compras.id+'-prv_id').setRawValue(vnombre);
			Ext.getCmp(compras.id+'-prv_ruc').setValue(vruc);
			Ext.getCmp(compras.id+'-prv_codigo').setValue(vcodigo);
			
		},
		
		fn_imprimir:function()
        {
			//alert("INI");
			document.getElementById('frmReporte-compras').action="movimientos/compras-lista-impresion";
			dt = Date.parseDate(Ext.getCmp(compras.id+'-fec_ini').getRawValue(), "d/m/Y");	
			document.getElementById('txtpar1').value = dt.format('Y-m-d');
			dt = Date.parseDate(Ext.getCmp(compras.id+'-fec_fin').getRawValue(), "d/m/Y");	
			document.getElementById('txtpar2').value = dt.format('Y-m-d');
			document.getElementById('txtpar3').value = Ext.getCmp(compras.id+'-doc_id_buscar').getValue();
			document.getElementById('txtpar4').value = Ext.getCmp(compras.id+'-numero_buscar').getValue();
			
			vOrden = Ext.getCmp(compras.id+'-grid_lista').store.getSortState( );			
			document.getElementById('txttitulo').value = "Listado de Compras";
			vFiltro = '';
			if(Ext.getCmp(compras.id+'-fec_ini').getRawValue()!=''){
				if(Ext.getCmp(compras.id+'-fec_ini').getRawValue()==Ext.getCmp(compras.id+'-fec_fin').getRawValue()){
					vFiltro = "Fecha : " + Ext.getCmp(compras.id+'-fec_ini').getRawValue();	
				}else{
					vFiltro = "Fecha : Desde " + Ext.getCmp(compras.id+'-fec_ini').getRawValue() + " al " + Ext.getCmp(compras.id+'-fec_fin').getRawValue();	
				}
				
			}
			if(Ext.getCmp(compras.id+'-doc_id_buscar').getValue()>0){
				if(vFiltro!=''){
					vFiltro=vFiltro + ', ';
				}
				vFiltro = vFiltro + "Documento : " + Ext.getCmp(compras.id+'-doc_id_buscar').getRawValue();
			}
			if(Ext.getCmp(compras.id+'-numero_buscar').getValue()!=''){
				if(vFiltro!=''){
					vFiltro=vFiltro + ', ';
				}
				vFiltro = vFiltro + " Buscar :" + Ext.getCmp(compras.id+'-numero_buscar').getValue();
			}
			document.getElementById('txtfiltro').value = 'FILTRO : ' + vFiltro;
			document.getElementById('txtsort').value = vOrden.field;
			document.getElementById('txtdir').value = vOrden.direction;
			
            document.getElementById('frmReporte-compras').submit();
        },
         
    }
    Ext.onReady(compras.init,compras);

</script>