<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('rpt_compras');
    rpt_compras={
        id:'rpt_compras',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_guardar=new Ext.Button({
                id:rpt_compras.id+'-btn_guardar',
                text:'Registrar',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            rpt_compras.fn_guardar();
                        }
                    }
            });
            
            var store_tienda_lista=new Ext.data.JsonStore({
                url:'maestros/tiendas-lista',
                root:'data',
                totalProperty:'total',
                fields:['tie_id','nombre','descripcion','telefono','direccion','precio','suc_id','estado']
            });

            //store_tienda_lista.load({params:{quitar:'SI'}});
            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                xtype:'panel',
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:rpt_compras.id+'-usr_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_tienda_lista,
                                id:rpt_compras.id+'-tie_id',
                                fieldLabel:'Elegir Tienda a dirigirse',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:220,
                                mode:'local',
                                valueField:'tie_id',
                                displayField:'nombre',
                                triggerAction:'all',
                                forceSelection:true,
								hidden:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:127,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'datefield',
                                id:rpt_compras.id+'-fecha',
                                emptyText:'Fecha',
                                width:120,
                                fieldLabel:'Fecha',
                                format:'d/m/Y',
                                altFormats : "d/m/Y",
                                itemCls: 'label01',
								allowBlank:false,
								disabled:true,
								value:'<?=date('d/m/Y')?>',
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'numberfield',
                                id:rpt_compras.id+'-valor_compra',
                                fieldLabel:'Valor compra',
                                itemCls: 'label01',
                                style:{marginLeft:'7px', textAlign:'right'},
                                width:80,
								allowNegative: false,
								decimalPrecision:4,
								maxValue: 4.0000,
						        minValue: 2.0000,
								value:'<?=$this->sesion->se_tc_c?>',
								allowBlank:false,
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'numberfield',
                                id:rpt_compras.id+'-valor_venta',
                                fieldLabel:'Valor venta',
                                itemCls: 'label01',
                                style:{marginLeft:'7px', textAlign:'right'},
                                width:80,
								allowNegative: false,
								decimalPrecision:4,
								maxValue: 4.0000,
						        minValue: 2.0000,
								value:'<?php echo $this->sesion->se_tc_v;?>',
								allowBlank:false
                            }
                        ]
                    }
                    
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_guardar,
                        ]
                    }],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'form',
                xtype: 'panel',
                width:'100%',
                autoScroll: true,  
                border:false,
                items:
                [
                    panel_form
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_rpt_compras',
                                        title:'Reporte de Compras', 
                                        width: 400,
                                        height:200,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
										modal:true,
                                        collapsible:false,
                                        draggable:true,
                                        onEsc:function(){Ext.getCmp('win_rpt_compras').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_rpt_compras').show();
                Ext.getCmp('win_rpt_compras').center();
                Ext.getCmp('win_rpt_compras').toFront();
                btn_guardar.setVisible(true);
        },
        fn_guardar:function()
        {
            
            Ext.Msg.wait('Guardando Tipo de Cambio ... por favor espere!');
            Ext.Ajax.request({
                url:'usuarios/seleccion-guardar',
                params:
                {
                    tie_id:0,
					tienda:'',
					fecha:Ext.util.Format.date(Ext.getCmp(rpt_compras.id+'-fecha').getValue(),'Y-m-d'),
					valor_compra:Ext.getCmp(rpt_compras.id+'-valor_compra').getValue(),
					valor_venta:Ext.getCmp(rpt_compras.id+'-valor_venta').getValue(),
                },
                success:function(response,options)
                {           
					var res = Ext.decode(response.responseText);
					Ext.Msg.hide();  
                    Ext.getCmp('win_rpt_compras').close();
            }
            });
        }
         
    }
    Ext.onReady(rpt_compras.init,rpt_compras);

</script>