<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('clave');
    clave={
        id:'clave',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_guardar=new Ext.Button({
                id:clave.id+'-btn_guardar',
                text:'Cambiar Clave',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            clave.fn_guardar();
                        }
                    }
            });
            
            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                xtype:'panel',
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:clave.id+'-usr_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
								inputType: 'password',
                                id:clave.id+'-clave_anterior',
                                fieldLabel:'Ingrese clave anterior',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:150,
								allowBlank:false
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
								inputType: 'password',
                                id:clave.id+'-clave_nueva',
                                fieldLabel:'Ingrese clave nueva',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:150,
								allowBlank:false
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
								inputType: 'password',
                                id:clave.id+'-confirmar_clave',
                                fieldLabel:'Repita clave nueva',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:150,
								allowBlank:false
                            }
                        ]
                    }
                    
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_guardar,
                        ]
                    }],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'form',
                xtype: 'panel',
                width:'100%',
                autoScroll: true,  
                border:false,
                items:
                [
                    panel_form
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_clave',
                                        title:'Cambio de Clave', 
                                        width: 350,
                                        height:180,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
										modal:true,
                                        collapsible:false,
                                        draggable:true,
                                        onEsc:function(){Ext.getCmp('win_clave').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_clave').show();
                Ext.getCmp('win_clave').center();
                Ext.getCmp('win_clave').toFront();
                btn_guardar.setVisible(true);
        },
        fn_guardar:function()
        {
            if(!Ext.getCmp(clave.id+'-clave_anterior').isValid())
            {
                og.msg("Error", "Ingrese la clave anterior");
                Ext.getCmp(clave.id+'-clave_anterior').focus(true,10);
                return false;
            }
			
			if(!Ext.getCmp(clave.id+'-clave_nueva').isValid())
            {
                og.msg("Error", "Ingrese la nueva clave");
                Ext.getCmp(clave.id+'-clave_nueva').focus(true,10);
                return false;
            }
			
			if(!Ext.getCmp(clave.id+'-confirmar_clave').isValid())
            {
                og.msg("Error", "Ingrese la Confirmacion de nueva clave");
                Ext.getCmp(clave.id+'-confirmar_clave').focus(true,10);
                return false;
            }
			
			if(Ext.getCmp(clave.id+'-clave_nueva').getValue() != Ext.getCmp(clave.id+'-confirmar_clave').getValue())
            {
                og.msg("Error", "Confirmacion de Clave no coincide");
                Ext.getCmp(clave.id+'-confirmar_clave').focus(true,10);
                return false;
            }
			
			if(Ext.getCmp(clave.id+'-clave_nueva').getValue() == Ext.getCmp(clave.id+'-clave_anterior').getValue())
            {
                og.msg("Error", "Nueva clave no puede ser la misma que la anterior");
                Ext.getCmp(clave.id+'-confirmar_clave').focus(true,10);
                return false;
            }
			
            Ext.Msg.wait('Clambiando clave ... por favor espere!');
            Ext.Ajax.request({
                url:'usuarios/clave-guardar',
                params:
                {
                    clave_anterior:Ext.getCmp(clave.id+'-clave_anterior').getValue(),
					clave_nueva:Ext.getCmp(clave.id+'-clave_nueva').getValue()
                },
                success:function(response,options)
                {           
					Ext.Msg.hide();
					var res = Ext.decode(response.responseText);
					if(res.success){
						og.msg("Ok","Se guardo nueva clave correctamente");
						
                    	Ext.getCmp('win_clave').close();
					}else{
						og.msg("Error",res.mensaje);
					}					
            }
            });
        }
         
    }
    Ext.onReady(clave.init,clave);

</script>