<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>.:Login -> Inventario :.</title>
        <link href="<?php echo PUBLIC_PATH;?>/images/favicon.ico" type="image/x-icon" rel="shortcut icon" />
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH;?>/css/login.css" type="text/css" media="screen" title="no title" charset="utf-8">
        <style type="text/css">
            .text-center{
                text-align:center
            }
        </style>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH;?>/js/ext-3.4.0/ext-core.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH;?>/js/ext-3.4.0/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH;?>/js/jquery/jquery-1.6.4.min.js"></script>
        <script type="text/javascript">
			
            Ext.ns('login');
            login={
                msn:'<?echo $_GET["msn"]; ?>',
                init:function(){
					alert("DENTRO");
                    Ext.select('div[class=enviar]').hover(
                        function(e,t){
                            Ext.get(this).addClass('enviar_hover');
                        },
                        function(e,t){
                            Ext.get(this).removeClass('enviar_hover');
                        }
                    );
                    Ext.get('user').on('change',function(e, t, o){
                        //login.getSistemas();
                    });
                    Ext.get('user').on('keypress',function(e, t, o){
                        if(e.getKey()==13){
                            Ext.fly('password').focus();
                        }
                    });
                    Ext.get('acceder_boton').on('click',function(obj, e){
                        login.acceder();
                    });
                    Ext.get('password').on('keypress',function(e, t, o){
                        if(e.getKey()==13){
                            login.acceder();
                        }
                    });
                    /*if(login.msn==1){
						Ext.get('error-sistema-login').update('<b>Error: Usuario y/o contraseña no coinciden...</b>');
						Ext.get('error-sistema-login').slideIn();
					}
					if(login.msn==2){
						alert(login.msn);
						Ext.get('error-sistema-login').update('<b>Error: Usted no tiene acceso en este horario, consulte con el Administrador......</b>');
						Ext.get('error-sistema-login').slideIn();
					} */
					alert("AQUI");
                    Ext.fly('user').focus(100);
					
					
					/*Ext.get('user').on(
						'blur',
						function(e,t) {
							alert(Ext.fly('user').getValue());
							//if(Ext.fly('user').getValue()<>''){
								//Ext.Msg.wait('Obteniendo Oficinas... por favor espere!');
								Ext.Ajax.request({
										url:'inicio/obtener',
										params:
										{
											user:Ext.fly('user').getValue(),
										},
										success:function(response,options)
										{        
											//Ext.Msg.hide();     
											alert(response.responseText);
										}
									});
							//}
						}
					);*/
					
					/*Ext.get('user').on(
						'blur',
						function(e,t) {
							alert("hola");
						}
					);*/
					
					/*var store_tie_lista=new Ext.data.JsonStore({
						url:'maestros/tiendas-lista',
						root:'data',
						totalProperty:'total',
						fields:['tie_id','nombre']
					});*/

					
					
                },
                acceder:function(){
					alert("ENTRA");
                    var nombre = Ext.get('user').getValue();
                    var clave = Ext.get('password').getValue();
                    if(nombre!='' && clave!='')
					{
                        document.formulario_login.submit();
                    }else{
                        if(nombre=='') Ext.get('error-user').slideIn();
                        if(clave=='') Ext.get('error-password').slideIn();
                    }
                }
            }
            Ext.onReady(login.init,login);
        </script>
    </head>
    <body>
        <div id="error-sistema-login"><b>Error: Usuario y/o contraseña no coinciden...</b></div>
        <div id="pantalla_fondo_login"></div>
            <div id="cuadro_login_01">
            <div class="adentro">
                <div class="adentro_texto">
                    <form action="<?php echo PUBLIC_PATH;?>/login/validar-usuario/" id="formulario_login" name="formulario_login" method="POST" accept-charset="utf-8">
                    <input type="hidden" name="estado" value="autentica" id="estado">
                    Ingrese sus datos para acceder al sistema.
                    <p>
                        <label>Usuario:</label>
                        <input type="text" name="user" class="campo" value="" id="user" autocomplete="off">
                        <div class="error" id="error-nombre">
                            Ingrese su nombre de Usuario
                        </div>
                    </p>
                    <p>
                        <label>Contrase&ntilde;a:</label>
                        <input type="password" name="password" class="campo" value="" id="password" autocomplete="off">
                        <div class="error" id="error-password">
                            Ingrese su password
                        </div>
                    </p>
                    <?php /*?><p>
                        <label>Oficina:</label>
                        <input type="text" name="txtoficina" value="" id="txtoficina">
                    </p><?php */?>
                    <p style="padding-left:50%; font-size:12px">
                        Fecha y Hora: <?=date('d/m/Y h:i:s')?>
                    </p>
                    <p align="center">
                        <div class="enviar" id="acceder_boton" ></div>
                    </p>
                    <p align="center">
                        <small>Copyright - Inventario, Derechos Reservados</small>
                    </p>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>