<form id="frmReporte-igv" name="frmReporte-igv" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
</form>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('igv');
    igv={
        id:'igv',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
			var btn_nuevo=new Ext.Button({
                id:igv.id+'-btn_nuevo',
                text:'Nuevo',
                iconCls:'btn_add_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(igv.id+'-panel_derecho').expand();
				Ext.getCmp(igv.id+'-panel_derecho').setVisible(true);
                            igv.fn_nuevo();
                        }
                    }
            });
            
            var btn_guardar=new Ext.Button({
                id:igv.id+'-btn_guardar',
                text:'Guardar',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            igv.fn_guardar();
                        }
                    }
            });
			
            var btn_actualizar=new Ext.Button({
                id:igv.id+'-btn_actualizar',
                text:'Actualizar',
                iconCls:'btn_update_log',
                listeners:
                    {
                        click:function()
                        {
                            igv.fn_actualizar();
                        }
                    }
            });
            
            var btn_editar=new Ext.Button({
                id:igv.id+'-btn_editar',
                text:'Editar',
                iconCls:'btn_edit_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            igv.fn_editar();
                        }
                    }
            });
            
            var btn_cancelar=new Ext.Button({
                id:igv.id+'-btn_cancelar',
                text:'Cancelar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(igv.id+'-panel_derecho').collapse();
							Ext.getCmp(igv.id+'-panel_derecho').setVisible(false);
                            igv.fn_habilitar(false,0);
                        }
                    }
            });
			
			var btn_eliminar=new Ext.Button({
                id:igv.id+'-btn_eliminar',
                text:'Eliminar',
                iconCls:'btn_delete_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
							igv.fn_eliminar();                           
                        }
                    }
            });
			
			var btn_imprimir=new Ext.Button({
                id:igv.id+'-btn_imprimir',
                text:'Imprimir',
                icon:'images/icon/printer.png',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea imprimir listado?', function(btn) {
                                if(btn == 'yes')
                                {
                                    igv.fn_imprimir();
                                }
                            });

                            
                        }
                    }
            });
            
            var store_igv_lista=new Ext.data.JsonStore({
                url:'tablas/igv-lista',
                root:'data',
                totalProperty:'total',
                fields:['igv_id','valor']
            });
            
            store_igv_lista.load();

            var store_usuarios_describe=new Ext.data.JsonStore({
                url:'tablas/igv-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });
            
            store_usuarios_describe.load({params:{table:'igv'}});
            
            var combo_usuarios_describe=new Ext.form.ComboBox({
                id:igv.id+'-combo_describe',
                store:store_usuarios_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
                mode:'local',
                width:100,
                editable:false
            });
            
            var grid_igv_lista = new Ext.grid.GridPanel({
                id:igv.id+'-grid_lista',
                store: store_igv_lista,
                singleSelect:true,
                columnLines:true,
                monitorResize:true,
                width:226,
                height:300,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'igv_id',width:25},
                    {header:'Valor',sortable :true,dataIndex:'valor',width:150, align:'right'}
                ]
                ,
                listeners:
                {
                    rowdblclick:function()
                    {
                        if(Ext.getCmp(igv.id+'-btn_editar').isVisible()){
							Ext.getCmp(igv.id+'-panel_derecho').expand();
				Ext.getCmp(igv.id+'-panel_derecho').setVisible(true);
                        	igv.fn_editar();
						}
                    },
					rowclick:function()
                    {
                        Ext.getCmp(igv.id+'-btn_editar').enable();
						Ext.getCmp(igv.id+'-btn_eliminar').enable();
                    }
                }
            });

            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                id:igv.id+'-formulario',
				xtype:'form',
				frame: true,
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:igv.id+'-igv_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'numberfield',
                                id:igv.id+'-valor',
                                fieldLabel:'Valor',
                                itemCls: 'label01',
								style:{marginLeft:'7px', textAlign:'right'},
                                width:50,
								allowBlank:false
                            }
                        ]
                    }
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            bodyStyle:'height:auto;width:70%;margin:auto;margin-top:10px;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'fit',
                xtype: 'panel',
                width:'760',
                autoScroll: true,  
                border:false,
                items:
                [
                    grid_igv_lista
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
            ,
            {  
                id:igv.id+'-panel_derecho',
                region: 'east',
                xtype: 'panel',
                collapsible:true,
                layout: 'form',
                split:true,
                collapsed:true,
                width:'790',
                border:false,
                items:
                [
                    panel_form
                ]  
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_igv',
                                        title:'igv', 
                                        width: 800,
                                        height:500,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
                                        collapsible:false,
                                        draggable:true,
                                        tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_nuevo, '-', btn_guardar, btn_actualizar, btn_editar,'-',btn_eliminar, btn_cancelar, '-', btn_imprimir,
                            combo_usuarios_describe,
                    new Ext.app.SearchField({
                        id:igv.id+'-buscar', 
                        emptyText : 'Valor a buscar...',
                        enableKeyEvents: true,
                        store: store_igv_lista,
                        hasSearch : false,
                        width: 120,
                        listeners:
                        {
                            specialkey:function(obj, e)
                            {
                                if (e.getKey() == 13)
                                {
									igv.fn_habilitar(false,0);
                                store_igv_lista.load({params:{campo:Ext.getCmp(igv.id+'-combo_describe').getValue(),query:Ext.getCmp(igv.id+'-buscar').getValue()}});
                                }
                            }
                        }
                    })
                    
                        ]
                    }],
                                        onEsc:function(){Ext.getCmp('win_igv').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_igv').show();
                Ext.getCmp('win_igv').center();
                Ext.getCmp('win_igv').toFront();
                igv.fn_habilitar(false,0);
                Ext.getCmp(igv.id+'-panel_derecho').collapse();
							Ext.getCmp(igv.id+'-panel_derecho').setVisible(false);
        },
		
		fn_nuevo:function()
        {            
            Ext.getCmp(igv.id+'-igv_id').setValue('');
			Ext.getCmp(igv.id+'-valor').setValue('');
                        
            igv.fn_habilitar(true,1);
        },
		
        fn_editar:function()
        {
            var rs=Ext.getCmp(igv.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.getCmp(igv.id+'-panel_derecho').expand();
				Ext.getCmp(igv.id+'-panel_derecho').setVisible(true);
                Ext.getCmp(igv.id+'-igv_id').setValue(rs.get('igv_id'));
                Ext.getCmp(igv.id+'-valor').setValue(rs.get('valor'));
                
                igv.fn_habilitar(true,2);
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
		
        fn_actualizar:function()
        {
            if(igv.fn_validar()){
				Ext.getCmp(igv.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/igv-actualizar',
					params:{ 
						igv_id:Ext.getCmp(igv.id+'-igv_id').getValue(),
						valor:Ext.getCmp(igv.id+'-valor').getValue()
					},
					waitTitle: 'Actualizando Informacion',
					waitMsg: 'Enviando datos..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(igv.id+'-panel_derecho').collapse();
							Ext.getCmp(igv.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							igv.fn_habilitar(false,0);
							Ext.getCmp(igv.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(igv.id+'-combo_describe').getValue(),query:Ext.getCmp(igv.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(igv.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(igv.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(igv.id+res.campo).focus(true,10);
					}
				});
				
				/*Ext.Ajax.request({
					url:'tablas/igv-actualizar',
					params:
					{
						igv_id:Ext.getCmp(igv.id+'-igv_id').getValue(),
						valor:Ext.getCmp(igv.id+'-valor').getValue()
					},
					success:function(response,options)
					{             
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(igv.id+'-panel_derecho').collapse();
							Ext.getCmp(igv.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							igv.fn_habilitar(false,0);
							Ext.getCmp(igv.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(igv.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
		
		fn_guardar:function()
        {
            if(igv.fn_validar()){
				Ext.getCmp(igv.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/igv-guardar',
					params:{ 
						valor:Ext.getCmp(igv.id+'-valor').getValue(),
					},
					waitTitle: 'Registro de ',
					waitMsg: 'Guardando Información..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(igv.id+'-panel_derecho').collapse();
							Ext.getCmp(igv.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							igv.fn_habilitar(false,0);
							Ext.getCmp(igv.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(igv.id+'-combo_describe').getValue(),query:Ext.getCmp(igv.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(igv.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(igv.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(igv.id+res.campo).focus(true,10);
					}
				});
				/*Ext.Ajax.request({
					url:'tablas/igv-guardar',
					params:
					{
						valor:Ext.getCmp(igv.id+'-valor').getValue(),
					},
					success:function(response,options)
					{ 
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(igv.id+'-panel_derecho').collapse();
							Ext.getCmp(igv.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							igv.fn_habilitar(false,0);
							Ext.getCmp(igv.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(igv.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
		
		fn_eliminar:function()
        {
            var rs=Ext.getCmp(igv.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.Msg.confirm('Alerta', 'Desea eliminar?<br>IGV :<br>' + rs.get('valor'), function(btn) {
					if(btn == 'yes')
					{
						Ext.Msg.wait('Eliminando igv... por favor espere!');
						Ext.Ajax.request({
							url:'tablas/igv-eliminar',
							params:
							{
								igv_id:rs.get('igv_id')
							},
							success:function(response,options)
							{            
								Ext.Msg.hide(); 
								var res = Ext.decode(response.responseText);
								if(res.success){
									og.msg("Ok","El registro se ha eliminado");
									igv.fn_habilitar(false,0);
									Ext.getCmp(igv.id+'-grid_lista').store.load();
								}else{
									og.msg("Error",res.mensaje);
									Ext.getCmp(igv.id+res.campo).focus(true,10);							
								}
							}
						});
					}
				 });
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
		
		fn_validar:function(){
			if(!Ext.getCmp(igv.id+'-valor').isValid())
            {
                og.msg("Error", "Ingrese el campo Valor");
                Ext.getCmp(igv.id+'-valor').focus(true,10);
                return false;
            }
			return true;
		},
		
		fn_imprimir:function()
        {
			document.getElementById('frmReporte-igv').action="tablas/igv-lista-impresion";
			document.getElementById('txtpar1').value = Ext.getCmp(igv.id+'-combo_describe').getValue();
			document.getElementById('txtpar2').value = Ext.getCmp(igv.id+'-buscar').getValue();
            document.getElementById('frmReporte-igv').submit();
        },
		
		fn_habilitar:function(sw, tipo)
        {
			if(!sw){
				Ext.getCmp(igv.id+'-btn_guardar').setVisible(sw);
				Ext.getCmp(igv.id+'-btn_actualizar').setVisible(sw);
			}else{
				if(tipo==1){
					Ext.getCmp(igv.id+'-btn_guardar').setVisible(sw);
					Ext.getCmp(igv.id+'-btn_actualizar').setVisible(!sw);
				}else{
					Ext.getCmp(igv.id+'-btn_guardar').setVisible(!sw);
					Ext.getCmp(igv.id+'-btn_actualizar').setVisible(sw);
				}
			}
			<?php if($this->acceso[1]=='Y'){?>
			Ext.getCmp(igv.id+'-btn_nuevo').setVisible(!sw);			
			<? } ?>
			Ext.getCmp(igv.id+'-btn_cancelar').setVisible(sw);
			<?php if($this->acceso[2]=='Y'){?>
			Ext.getCmp(igv.id+'-btn_editar').setVisible(!sw);
			<? } ?>
			<?php if($this->acceso[3]=='Y'){?>
			Ext.getCmp(igv.id+'-btn_eliminar').setVisible(!sw);
			<? } ?>

			Ext.getCmp(igv.id+'-btn_editar').disable();
			Ext.getCmp(igv.id+'-btn_eliminar').disable();
			
			Ext.getCmp(igv.id+'-buscar').setVisible(!sw);			
			Ext.getCmp(igv.id+'-combo_describe').setVisible(!sw);
			
			Ext.getCmp(igv.id+'-btn_imprimir').setVisible(!sw);			
        }
         
    }
    Ext.onReady(igv.init,igv);

</script>