<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('numeracion');
    numeracion={
        id:'numeracion',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_nuevo=new Ext.Button({
                id:numeracion.id+'-btn_nuevo',
                text:'Nuevo',
                iconCls:'btn_add_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(numeracion.id+'-panel_derecho').expand();
				Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(true);
                            numeracion.fn_nuevo();
                        }
                    }
            });
            
            var btn_guardar=new Ext.Button({
                id:numeracion.id+'-btn_guardar',
                text:'Guardar',
                iconCls:'btn_save_log',
                disabled:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(numeracion.id+'-panel_derecho').collapse();
							Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(false);
                            numeracion.fn_guardar();
                        }
                    }
            });
            
            var btn_actualizar=new Ext.Button({
                id:numeracion.id+'-btn_actualizar',
                text:'Actualizar',
                iconCls:'btn_update_log',
                disabled:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(numeracion.id+'-panel_derecho').collapse();
							Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(false);
                            numeracion.fn_actualizar();
                        }
                    }
            });
            
            var btn_editar=new Ext.Button({
                id:numeracion.id+'-btn_editar',
                text:'Editar',
                iconCls:'btn_edit_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(numeracion.id+'-panel_derecho').expand();
				Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(true);
                            numeracion.fn_editar();
                        }
                    }
            });
            
            var btn_cancelar=new Ext.Button({
                id:numeracion.id+'-btn_cancelar',
                text:'Cancelar',
                iconCls:'btn_cancel_log',
                disabled:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(numeracion.id+'-panel_derecho').collapse();
							Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(false);
                            numeracion.fn_cancelar();
                        }
                    }
            });
            
            var btn_eliminar=new Ext.Button({
                id:numeracion.id+'-btn_eliminar',
                text:'Eliminar',
                iconCls:'btn_delete_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea eliminar?', function(btn) {
                                if(btn == 'yes')
                                {
                                    numeracion.fn_eliminar();
                                }
                            });

                            
                        }
                    }
            });
            
            var store_numeracion_lista=new Ext.data.JsonStore({
                url:'tablas/numeracion-lista',
                root:'data',
                totalProperty:'total',
                fields:['ust_id','nombre','activo']
            });
            
            store_numeracion_lista.load();

            var store_usuarios_describe=new Ext.data.JsonStore({
                url:'usuarios/usuarios-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });
            
            store_usuarios_describe.load({params:{table:'numeracion'}});
            
            var combo_usuarios_describe=new Ext.form.ComboBox({
                id:numeracion.id+'-combo_describe',
                store:store_usuarios_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
                mode:'local',
                width:100,
                editable:false
            });
            
            var grid_numeracion_lista = new Ext.grid.GridPanel({
                id:numeracion.id+'-grid_lista',
                store: store_numeracion_lista,
                singleSelect:true,
                columnLines:true,
                monitorResize:true,
                width:226,
                height:300,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'ust_id',width:25},
                    {header:'Nombres',sortable :true,dataIndex:'nombre',width:150},
                    {header:'Activo',sortable :true,dataIndex:'activo',width:150,hidden:true},
                ]
                ,
                listeners:
                {
                    rowdblclick:function()
                    {
                        Ext.getCmp(numeracion.id+'-panel_derecho').expand();
				Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(true);
                        numeracion.fn_editar();
                    }
                }
            });

            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                id:numeracion.id+'-formulario',
				xtype:'form',
				frame: true,
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:numeracion.id+'-ust_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:numeracion.id+'-codigo',
                                fieldLabel:'Código',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:80
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:numeracion.id+'-descripcion',
                                fieldLabel:'Descripción',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:250
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:numeracion.id+'-numeracion',
                                fieldLabel:'Numeración',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:80
                            }
                        ]
                    }
                    
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            bodyStyle:'height:auto;width:70%;margin:auto;margin-top:10px;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'fit',
                xtype: 'panel',
                width:'760',
                autoScroll: true,  
                border:false,
                items:
                [
                    grid_numeracion_lista
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
            ,
            {  
                id:numeracion.id+'-panel_derecho',
                region: 'east',
                xtype: 'panel',
                collapsible:true,
                layout: 'form',
                split:true,
                collapsed:true,
                width:'790',
                border:false,
                items:
                [
                    panel_form
                ]  
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_numeracion',
                                        title:'Numeración', 
                                        width: 800,
                                        height:500,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
                                        collapsible:false,
                                        draggable:true,
                                        tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_nuevo,'-',btn_guardar,'-',btn_actualizar,'-',btn_editar,'-',btn_eliminar,btn_cancelar,
                            combo_usuarios_describe,'-',
                    new Ext.app.SearchField({
                        id:numeracion.id+'-buscar', 
                        emptyText : 'Valor a buscar...',
                        enableKeyEvents: true,
                        store: store_numeracion_lista,
                        hasSearch : false,
                        width: 120,
                        listeners:
                        {
                            specialkey:function(obj, e)
                            {
                                if (e.getKey() == 13)
                                {
                                store_numeracion_lista.load({params:{campo:Ext.getCmp(numeracion.id+'-combo_describe').getValue(),query:Ext.getCmp(numeracion.id+'-buscar').getValue()}});
                                }
                            }
                        }
                    })
                    
                        ]
                    }],
                                        onEsc:function(){Ext.getCmp('win_numeracion').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_numeracion').show();
                Ext.getCmp('win_numeracion').center();
                Ext.getCmp('win_numeracion').toFront();
                btn_cancelar.setVisible(false);
        },
        fn_cancelar:function()
        {
            Ext.getCmp(numeracion.id+'-ust_id').setValue('');
            Ext.getCmp(numeracion.id+'-nombre').setValue('');
            Ext.getCmp(numeracion.id+'-estado').items.items[0].setValue(true);
            Ext.getCmp(numeracion.id+'-estado').items.items[1].setValue(false);
            Ext.getCmp(numeracion.id+'-btn_nuevo').enable();
            Ext.getCmp(numeracion.id+'-btn_guardar').disable();
            Ext.getCmp(numeracion.id+'-btn_actualizar').disable();
            Ext.getCmp(numeracion.id+'-btn_editar').enable();
            Ext.getCmp(numeracion.id+'-btn_eliminar').enable();
            Ext.getCmp(numeracion.id+'-btn_eliminar').setVisible(true);
            Ext.getCmp(numeracion.id+'-btn_cancelar').disable();
            Ext.getCmp(numeracion.id+'-btn_cancelar').setVisible(false);
        },
        fn_limpiar:function()
        {
            Ext.getCmp(numeracion.id+'-ust_id').setValue('');
            Ext.getCmp(numeracion.id+'-nombre').setValue('');
            Ext.getCmp(numeracion.id+'-estado').items.items[0].setValue(true);
            Ext.getCmp(numeracion.id+'-estado').items.items[1].setValue(false);
        },
        fn_nuevo:function()
        {
            Ext.getCmp(numeracion.id+'-ust_id').setValue('');
            Ext.getCmp(numeracion.id+'-nombre').setValue('');            
            Ext.getCmp(numeracion.id+'-estado').items.items[0].setValue(true);
            Ext.getCmp(numeracion.id+'-estado').items.items[1].setValue(false);
            
            Ext.getCmp(numeracion.id+'-btn_nuevo').disable();
            Ext.getCmp(numeracion.id+'-btn_guardar').enable();
            Ext.getCmp(numeracion.id+'-btn_actualizar').disable();
            Ext.getCmp(numeracion.id+'-btn_editar').disable();
            Ext.getCmp(numeracion.id+'-btn_eliminar').disable();
            Ext.getCmp(numeracion.id+'-btn_eliminar').setVisible(false);
            Ext.getCmp(numeracion.id+'-btn_cancelar').enable();
            Ext.getCmp(numeracion.id+'-btn_cancelar').setVisible(true);
        },
        fn_editar:function()
        {
            var rs=Ext.getCmp(numeracion.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
                Ext.getCmp(numeracion.id+'-ust_id').setValue(rs.get('ust_id'));
                Ext.getCmp(numeracion.id+'-nombre').setValue(rs.get('nombre'));
                Ext.getCmp(numeracion.id+'-estado').setValue(rs.get('activo'));
                
                Ext.getCmp(numeracion.id+'-btn_nuevo').disable();
                Ext.getCmp(numeracion.id+'-btn_guardar').disable();
                Ext.getCmp(numeracion.id+'-btn_actualizar').enable();
                Ext.getCmp(numeracion.id+'-btn_editar').enable();
                Ext.getCmp(numeracion.id+'-btn_eliminar').disable();
                Ext.getCmp(numeracion.id+'-btn_eliminar').setVisible(false);
                Ext.getCmp(numeracion.id+'-btn_cancelar').enable();
                Ext.getCmp(numeracion.id+'-btn_cancelar').setVisible(true);
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
        fn_actualizar:function()
        {
            if(Ext.getCmp(numeracion.id+'-nombre').getValue()=="")
            {
                og.msg("Error", "Ingrese el campo Nombres");
                Ext.getCmp(numeracion.id+'-nombre').focus(true,10);
                return false;
            }
			Ext.Msg.wait('Actualizando numeracion... por favor espere!');
            Ext.Ajax.request({
                url:'tablas/numeracion-actualizar',
                params:
                {
                    ust_id:Ext.getCmp(numeracion.id+'-ust_id').getValue(),
                    nombre:Ext.getCmp(numeracion.id+'-nombre').getValue(),
                    estado:Ext.getCmp(numeracion.id+'-estado').getValue().getGroupValue()
                },
                success:function(response,options)
                {         
					Ext.Msg.hide();    
                    var res = Ext.decode(response.responseText);
                    numeracion.fn_limpiar();
                    Ext.getCmp(numeracion.id+'-btn_nuevo').enable();
                    Ext.getCmp(numeracion.id+'-btn_guardar').disable();
                    Ext.getCmp(numeracion.id+'-btn_actualizar').disable();
                    Ext.getCmp(numeracion.id+'-btn_editar').enable();
                    Ext.getCmp(numeracion.id+'-btn_eliminar').enable();
                    Ext.getCmp(numeracion.id+'-btn_eliminar').setVisible(true);
                    Ext.getCmp(numeracion.id+'-btn_cancelar').disable();
                    Ext.getCmp(numeracion.id+'-btn_cancelar').setVisible(false);
                    og.msg("Ok","El registro se ha actualizado");
                    Ext.getCmp(numeracion.id+'-grid_lista').store.load();
            }
            });
        },
        fn_guardar:function()
        {
            if(Ext.getCmp(numeracion.id+'-nombre').getValue()=="")
            {
                og.msg("Error", "Ingrese el campo Nombres");
                Ext.getCmp(numeracion.id+'-nombre').focus(true,10);
                return false;
            }
				Ext.getCmp(numeracion.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/numeracion-guardar',
					params:{ 
						nombre:Ext.getCmp(numeracion.id+'-nombre').getValue(),
                    	estado:Ext.getCmp(numeracion.id+'-estado').getValue().getGroupValue()
					},
					waitTitle: 'Registro de ',
					waitMsg: 'Guardando Información..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(numeracion.id+'-panel_derecho').collapse();
							Ext.getCmp(numeracion.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							numeracion.fn_habilitar(false,0);
							Ext.getCmp(numeracion.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(numeracion.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(numeracion.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
							});
							
							
					}
				});
            /*Ext.Ajax.request({
                url:'tablas/numeracion-guardar',
                params:
                {
                    nombre:Ext.getCmp(numeracion.id+'-nombre').getValue(),
                    estado:Ext.getCmp(numeracion.id+'-estado').getValue().getGroupValue()
                },
                success:function(response,options)
                {             
                    var res = Ext.decode(response.responseText);
                    numeracion.fn_limpiar();
                    Ext.getCmp(numeracion.id+'-btn_nuevo').enable();
                    Ext.getCmp(numeracion.id+'-btn_guardar').disable();
                    Ext.getCmp(numeracion.id+'-btn_actualizar').disable();
                    Ext.getCmp(numeracion.id+'-btn_editar').enable();
                    Ext.getCmp(numeracion.id+'-btn_eliminar').enable();
                    Ext.getCmp(numeracion.id+'-btn_eliminar').setVisible(true);
                    Ext.getCmp(numeracion.id+'-btn_cancelar').disable();
                    Ext.getCmp(numeracion.id+'-btn_cancelar').setVisible(false);
                    og.msg("Ok","El registro se ha guardado");
                    Ext.getCmp(numeracion.id+'-grid_lista').store.load();
            	}
            });*/
        },
        fn_eliminar:function()
        {
            var rs=Ext.getCmp(numeracion.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.Msg.wait('Eliminando numeración... por favor espere!');
                Ext.Ajax.request({
                    url:'tablas/numeracion-eliminar',
                    params:
                    {
                        ust_id:rs.get('ust_id')
                    },
                    success:function(response,options)
                    {         
						Ext.Msg.hide();    
                        var res = Ext.decode(response.responseText);
                        numeracion.fn_limpiar();
                        Ext.getCmp(numeracion.id+'-btn_nuevo').enable();
                        Ext.getCmp(numeracion.id+'-btn_guardar').disable();
                        Ext.getCmp(numeracion.id+'-btn_actualizar').disable();
                        Ext.getCmp(numeracion.id+'-btn_editar').enable();
                        Ext.getCmp(numeracion.id+'-btn_eliminar').enable();
                        Ext.getCmp(numeracion.id+'-btn_eliminar').setVisible(true);
                        Ext.getCmp(numeracion.id+'-btn_cancelar').disable();
                        Ext.getCmp(numeracion.id+'-btn_cancelar').setVisible(false);
                        og.msg("Ok","El registro se ha guardado");
                        Ext.getCmp(numeracion.id+'-grid_lista').store.load();
                    }
                });
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        }
         
    }
    Ext.onReady(numeracion.init,numeracion);

</script>