<form id="frmReporte-lineas" name="frmReporte-lineas" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
</form>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('lineas');
    lineas={
        id:'lineas',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_nuevo=new Ext.Button({
                id:lineas.id+'-btn_nuevo',
                text:'Nuevo',
                iconCls:'btn_add_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(lineas.id+'-panel_derecho').expand();
				Ext.getCmp(lineas.id+'-panel_derecho').setVisible(true);
                            lineas.fn_nuevo();
                        }
                    }
            });
            
            var btn_guardar=new Ext.Button({
                id:lineas.id+'-btn_guardar',
                text:'Guardar',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            lineas.fn_guardar();
                        }
                    }
            });
            
            var btn_actualizar=new Ext.Button({
                id:lineas.id+'-btn_actualizar',
                text:'Actualizar',
                iconCls:'btn_update_log',
                listeners:
                    {
                        click:function()
                        {
                            lineas.fn_actualizar();
                        }
                    }
            });
            
            var btn_editar=new Ext.Button({
                id:lineas.id+'-btn_editar',
                text:'Editar',
                iconCls:'btn_edit_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            lineas.fn_editar();
                        }
                    }
            });
            
            var btn_cancelar=new Ext.Button({
                id:lineas.id+'-btn_cancelar',
                text:'Cancelar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(lineas.id+'-panel_derecho').collapse();
							Ext.getCmp(lineas.id+'-panel_derecho').setVisible(false);
                            lineas.fn_habilitar(false,0);
                        }
                    }
            });
            
            var btn_eliminar=new Ext.Button({
                id:lineas.id+'-btn_eliminar',
                text:'Eliminar',
                iconCls:'btn_delete_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
							lineas.fn_eliminar();
                        }
                    }
            });
			
			var btn_imprimir=new Ext.Button({
                id:lineas.id+'-btn_imprimir',
                text:'Imprimir',
                icon:'images/icon/printer.png',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea imprimir listado?', function(btn) {
                                if(btn == 'yes')
                                {
                                    lineas.fn_imprimir();
                                }
                            });

                            
                        }
                    }
            });
            
            var store_familias_lista=new Ext.data.JsonStore({
                url:'tablas/familias-lista',
                root:'data',
                totalProperty:'total',
                fields:['fam_id','nombre']
            });
            
            store_familias_lista.load();
            
            var store_lineas_lista=new Ext.data.JsonStore({
                url:'tablas/lineas-lista',
                root:'data',
                totalProperty:'total',
                fields:['lin_id','nombre','fam_id','fam_nom', 'codigo']
            });
            
            store_lineas_lista.load();

            var store_usuarios_describe=new Ext.data.JsonStore({
                url:'usuarios/usuarios-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });
            
            store_usuarios_describe.load({params:{table:'lineas'}});
            
            var combo_usuarios_describe=new Ext.form.ComboBox({
                id:lineas.id+'-combo_describe',
                store:store_usuarios_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
                mode:'local',
                width:100,
                editable:false
            });
            
            var grid_lineas_lista = new Ext.grid.GridPanel({
                id:lineas.id+'-grid_lista',
                store: store_lineas_lista,
                singleSelect:true,
                columnLines:true,
                monitorResize:true,
                width:226,
                height:300,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'lin_id',width:25},
                    {header:'Codigo',sortable :true,dataIndex:'codigo',width:150},
					{header:'Nombres',sortable :true,dataIndex:'nombre',width:200},
                    {header:'Familia Id',sortable :true,dataIndex:'fam_id',width:150,hidden:true},
					{header:'Familia',sortable :true,dataIndex:'fam_nom',width:150},
                ]
                ,
                listeners:
                {
                    rowdblclick:function()
                    {
                        if(Ext.getCmp(lineas.id+'-btn_editar').isVisible()){
							Ext.getCmp(lineas.id+'-panel_derecho').expand();
				Ext.getCmp(lineas.id+'-panel_derecho').setVisible(true);
                        	lineas.fn_editar();
						}
                    },
					rowclick:function()
                    {
                        Ext.getCmp(lineas.id+'-btn_editar').enable();
						Ext.getCmp(lineas.id+'-btn_eliminar').enable();
                    }
                }
            });

            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                id:lineas.id+'-formulario',
				xtype:'form',
				frame: true,
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:lineas.id+'-lin_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:lineas.id+'-codigo',
                                fieldLabel:'Código',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:80,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:lineas.id+'-nombre',
                                fieldLabel:'Descripción',
                                itemCls: 'label01',
								style: {textTransform: "uppercase", marginLeft:"7px"},
                                width:350,
								allowBlank:false
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'combo',
                                store:store_familias_lista,
                                id:lineas.id+'-fam_id',
                                fieldLabel:'Familia',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:350,
                                mode:'local',
                                valueField:'fam_id',
                                displayField:'nombre',
                                triggerAction:'all',
                                forceSelection:true,
								allowBlank:false
                            }
                        ]
                    }
                ]
            }
            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',
            bodyStyle:'height:auto;width:70%;margin:auto;margin-top:10px;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'fit',
                xtype: 'panel',
                width:'760',
                autoScroll: true,  
                border:false,
                items:
                [
                    grid_lineas_lista
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
            ,
            {  
                id:lineas.id+'-panel_derecho',
                region: 'east',
                xtype: 'panel',
                collapsible:true,
                layout: 'form',
                split:true,
                collapsed:true,
                width:'790',
                border:false,
                items:
                [
                    panel_form
                ]  
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_lineas',
                                        title:'Líneas', 
                                        width: 800,
                                        height:500,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
                                        collapsible:false,
                                        draggable:true,
                                        tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_nuevo,'-',btn_guardar,btn_actualizar,btn_editar,'-',btn_eliminar,btn_cancelar, '-', btn_imprimir,
                            combo_usuarios_describe,
                    new Ext.app.SearchField({
                        id:lineas.id+'-buscar', 
                        emptyText : 'Valor a buscar...',
                        enableKeyEvents: true,
                        store: store_lineas_lista,
                        hasSearch : false,
                        width: 120,
                        listeners:
                        {
                            specialkey:function(obj, e)
                            {
                                if (e.getKey() == 13)
                                {
									lineas.fn_habilitar(false,0);
                                store_lineas_lista.load({params:{campo:Ext.getCmp(lineas.id+'-combo_describe').getValue(),query:Ext.getCmp(lineas.id+'-buscar').getValue()}});
                                }
                            }
                        }
                    })
                    
                        ]
                    }],
                                        onEsc:function(){Ext.getCmp('win_lineas').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_lineas').show();
                Ext.getCmp('win_lineas').center();
                Ext.getCmp('win_lineas').toFront();
                lineas.fn_habilitar(false,0);
        },

        fn_nuevo:function()
        {
			Ext.Msg.wait('Generando código de linea... por favor espere!');
            Ext.Ajax.request({
                    url:'tablas/lineas-codigo',
                    params:
                    {
                        table:'lineas'
                    },
                    success:function(response,options)
                    {             
						Ext.Msg.hide();
                        var res = Ext.decode(response.responseText);
                        var numero="0000"+res.AUTO_INCREMENT;
                        var codigo="LI"+numero.substr(numero.length-4,4)
                        Ext.getCmp(lineas.id+'-codigo').setValue(codigo);
                    }
                });
                
            Ext.getCmp(lineas.id+'-lin_id').setValue('');
			Ext.getCmp(lineas.id+'-nombre').setValue('');
			Ext.getCmp(lineas.id+'-fam_id').setValue('');
            lineas.fn_habilitar(true,1);
        },
        fn_editar:function()
        {
            var rs=Ext.getCmp(lineas.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.getCmp(lineas.id+'-panel_derecho').expand();
				Ext.getCmp(lineas.id+'-panel_derecho').setVisible(true);
                Ext.getCmp(lineas.id+'-lin_id').setValue(rs.get('lin_id'));
                Ext.getCmp(lineas.id+'-codigo').setValue(rs.get('codigo'));
				Ext.getCmp(lineas.id+'-nombre').setValue(rs.get('nombre'));
				if(rs.get('fam_id')==null){
                	Ext.getCmp(lineas.id+'-fam_id').setValue("");
				}else{
					Ext.getCmp(lineas.id+'-fam_id').setValue(rs.get('fam_id'));
				}
                
                lineas.fn_habilitar(true,2);
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
        fn_actualizar:function()
        {
			if(lineas.fn_validar()){
				Ext.getCmp(lineas.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/lineas-actualizar',
					params:{ 
						lin_id:Ext.getCmp(lineas.id+'-lin_id').getValue(),
						codigo:Ext.getCmp(lineas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(lineas.id+'-nombre').getValue().toUpperCase(),
						fam_id:Ext.getCmp(lineas.id+'-fam_id').getValue()
					},
					waitTitle: 'Actualizando Informacion',
					waitMsg: 'Enviando datos..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(lineas.id+'-panel_derecho').collapse();
							Ext.getCmp(lineas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							lineas.fn_habilitar(false,0);
							Ext.getCmp(lineas.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(lineas.id+'-combo_describe').getValue(),query:Ext.getCmp(lineas.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(lineas.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(lineas.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(lineas.id+res.campo).focus(true,10);
					}
				});
				/*Ext.Ajax.request({
					url:'tablas/lineas-actualizar',
					params:
					{
						lin_id:Ext.getCmp(lineas.id+'-lin_id').getValue(),
						codigo:Ext.getCmp(lineas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(lineas.id+'-nombre').getValue().toUpperCase(),
						fam_id:Ext.getCmp(lineas.id+'-fam_id').getValue()
					},
					success:function(response,options)
					{             
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(lineas.id+'-panel_derecho').collapse();
							Ext.getCmp(lineas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							lineas.fn_habilitar(false,0);
							Ext.getCmp(lineas.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(lineas.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
        fn_guardar:function()
        {
			if(lineas.fn_validar()){
				Ext.getCmp(lineas.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/lineas-guardar',
					params:{ 
						codigo:Ext.getCmp(lineas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(lineas.id+'-nombre').getValue().toUpperCase(),
						fam_id:Ext.getCmp(lineas.id+'-fam_id').getValue()
					},
					waitTitle: 'Registro de ',
					waitMsg: 'Guardando Información..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(lineas.id+'-panel_derecho').collapse();
							Ext.getCmp(lineas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							lineas.fn_habilitar(false,0);
							Ext.getCmp(lineas.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(lineas.id+'-combo_describe').getValue(),query:Ext.getCmp(lineas.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(lineas.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(lineas.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(lineas.id+res.campo).focus(true,10);
					}
				});
				/*Ext.Ajax.request({
					url:'tablas/lineas-guardar',
					params:
					{
						codigo:Ext.getCmp(lineas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(lineas.id+'-nombre').getValue().toUpperCase(),
						fam_id:Ext.getCmp(lineas.id+'-fam_id').getValue()
					},
					success:function(response,options)
					{             
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(lineas.id+'-panel_derecho').collapse();
							Ext.getCmp(lineas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							lineas.fn_habilitar(false,0);
							Ext.getCmp(lineas.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(lineas.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
        fn_eliminar:function()
        {
            var rs=Ext.getCmp(lineas.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.Msg.confirm('Alerta', 'Desea eliminar?<br>Linea :<br>' + rs.get('nombre'), function(btn) {
					if(btn == 'yes')
					{
						Ext.Msg.wait('Eliminando linea... por favor espere!');
						Ext.Ajax.request({
							url:'tablas/lineas-eliminar',
							params:
							{
								lin_id:rs.get('lin_id')
							},
							success:function(response,options)
							{       
								Ext.Msg.hide();      
								var res = Ext.decode(response.responseText);
								if(res.success){
									og.msg("Ok","El registro se ha eliminado");
									lineas.fn_habilitar(false,0);
									Ext.getCmp(lineas.id+'-grid_lista').store.load();
								}else{
									og.msg("Error",res.mensaje);
									Ext.getCmp(lineas.id+res.campo).focus(true,10);							
								}
							}
						});
					}
				});
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
		
		fn_validar:function(){
			if(!Ext.getCmp(lineas.id+'-nombre').isValid())
            {
                og.msg("Error", "Ingrese el campo Nombres");
                Ext.getCmp(lineas.id+'-nombre').focus(true,10);
                return false;
            }
			if(!Ext.getCmp(lineas.id+'-fam_id').isValid())
            {
                og.msg("Error", "Ingrese el campo Familia");
                Ext.getCmp(lineas.id+'-fam_id').focus(true,10);
                return false;
            }
			return true;			
		},
		fn_imprimir:function()
        {
			document.getElementById('frmReporte-lineas').action="tablas/lineas-lista-impresion";
			document.getElementById('txtpar1').value = Ext.getCmp(lineas.id+'-combo_describe').getValue();
			document.getElementById('txtpar2').value = Ext.getCmp(lineas.id+'-buscar').getValue();
            document.getElementById('frmReporte-lineas').submit();
        },
		
		fn_habilitar:function(sw, tipo)
        {
			if(!sw){
				Ext.getCmp(lineas.id+'-btn_guardar').setVisible(sw);
				Ext.getCmp(lineas.id+'-btn_actualizar').setVisible(sw);
			}else{
				if(tipo==1){
					Ext.getCmp(lineas.id+'-btn_guardar').setVisible(sw);
					Ext.getCmp(lineas.id+'-btn_actualizar').setVisible(!sw);
				}else{
					Ext.getCmp(lineas.id+'-btn_guardar').setVisible(!sw);
					Ext.getCmp(lineas.id+'-btn_actualizar').setVisible(sw);
				}
			}
			<?php if($this->acceso[1]=='Y'){?>
			Ext.getCmp(lineas.id+'-btn_nuevo').setVisible(!sw);			
			<? } ?>
			Ext.getCmp(lineas.id+'-btn_cancelar').setVisible(sw);
			<?php if($this->acceso[2]=='Y'){?>
			Ext.getCmp(lineas.id+'-btn_editar').setVisible(!sw);
			<? } ?>
			<?php if($this->acceso[3]=='Y'){?>
			Ext.getCmp(lineas.id+'-btn_eliminar').setVisible(!sw);
			<? } ?>

			if(Ext.getCmp(lineas.id+'-grid_lista').getSelectionModel().getSelected()){
				Ext.getCmp(lineas.id+'-btn_editar').enable();
				Ext.getCmp(lineas.id+'-btn_eliminar').enable();
			}else{			
				Ext.getCmp(lineas.id+'-btn_editar').disable();
				Ext.getCmp(lineas.id+'-btn_eliminar').disable();
			}
			Ext.getCmp(lineas.id+'-buscar').setVisible(!sw);			
			Ext.getCmp(lineas.id+'-combo_describe').setVisible(!sw);
			
			Ext.getCmp(lineas.id+'-btn_imprimir').setVisible(!sw);			
        }
         
    }
    Ext.onReady(lineas.init,lineas);

</script>