<form id="frmReporte" name="frmReporte" method="post" action="" target="_blank">
  <input type="hidden" name="txtpar1" id="txtpar1" />
  <input type="hidden" name="txtpar2" id="txtpar2" />
</form>
<script type="text/javascript"> 
    var tab = Ext.getCmp(inicio.id+'-tabContent');
    //if(!Ext.getCmp('tiponovedades-tab')){
    Ext.ns('marcas');
    marcas={
        id:'marcas',
        init:function(){
            Ext.Ajax.timeout = 180000;
            Ext.QuickTips.init();
            
            var btn_nuevo=new Ext.Button({
                id:marcas.id+'-btn_nuevo',
                text:'Nuevo',
                iconCls:'btn_add_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(marcas.id+'-panel_derecho').expand();
				Ext.getCmp(marcas.id+'-panel_derecho').setVisible(true);
                            marcas.fn_nuevo();
                        }
                    }
            });
            
            var btn_guardar=new Ext.Button({
                id:marcas.id+'-btn_guardar',
                text:'Guardar',
                iconCls:'btn_save_log',
                listeners:
                    {
                        click:function()
                        {
                            marcas.fn_guardar();
                        }
                    }
            });
            
            var btn_actualizar=new Ext.Button({
                id:marcas.id+'-btn_actualizar',
                text:'Actualizar',
                iconCls:'btn_update_log',
                listeners:
                    {
                        click:function()
                        {
                            marcas.fn_actualizar();
                        }
                    }
            });
            
            var btn_editar=new Ext.Button({
                id:marcas.id+'-btn_editar',
                text:'Editar',
                iconCls:'btn_edit_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
                            marcas.fn_editar();
                        }
                    }
            });
            
            var btn_cancelar=new Ext.Button({
                id:marcas.id+'-btn_cancelar',
                text:'Cancelar',
                iconCls:'btn_cancel_log',
                listeners:
                    {
                        click:function()
                        {
                            Ext.getCmp(marcas.id+'-panel_derecho').collapse();
							Ext.getCmp(marcas.id+'-panel_derecho').setVisible(false);
                            marcas.fn_habilitar(false,0);
                        }
                    }
            });
            
            var btn_eliminar=new Ext.Button({
                id:marcas.id+'-btn_eliminar',
                text:'Eliminar',
                iconCls:'btn_delete_log',
				hidden:true,
                listeners:
                    {
                        click:function()
                        {
							marcas.fn_eliminar();                           
                        }
                    }
            });
			
			var btn_imprimir=new Ext.Button({
                id:marcas.id+'-btn_imprimir',
                text:'Imprimir',
                icon:'images/icon/printer.png',
                listeners:
                    {
                        click:function()
                        {
                            Ext.Msg.confirm('Alerta', 'Desea imprimir listado?', function(btn) {
                                if(btn == 'yes')
                                {
                                    marcas.fn_imprimir();
                                }
                            });

                            
                        }
                    }
            });
            
            var store_marcas_lista=new Ext.data.JsonStore({
                url:'tablas/marcas-lista',
                root:'data',
                totalProperty:'total',
                fields:['mar_id', 'codigo','nombre','activo'],
				remoteSort:true,				
				sortInfo: {field:'nombre', direction:'asc'}
            });
            
            store_marcas_lista.load();

            var store_marcas_describe=new Ext.data.JsonStore({
                url:'usuarios/usuarios-describe',
                root:'data',
                totalProperty:'total',
                fields:['Field']
            });
			
			var combo_marcas_describe=new Ext.form.ComboBox({
                id:marcas.id+'-combo_describe',
                store:store_marcas_describe,
                valueField:'Field',
                displayField:'Field',
                triggerAction:'all',
                emptyText:'Campo',
                mode:'local',
                width:100,
                editable:false
            });
			
			var txt_busqueda=new Ext.app.SearchField({
				id:marcas.id+'-buscar', 
				emptyText : 'Valor a buscar...',
				enableKeyEvents: true,
				store: store_marcas_lista,
				hasSearch : false,
				width: 120,
				listeners:
				{
					specialkey:function(obj, e)
					{
						if (e.getKey() == 13)
						{
						marcas.fn_habilitar(false,0);
						store_marcas_lista.load({params:{campo:Ext.getCmp(marcas.id+'-combo_describe').getValue(),query:Ext.getCmp(marcas.id+'-buscar').getValue(),start:0,limit:100}});
						}
					}
				}
			});
			
			var pager = new Ext.PagingToolbar({
                id:marcas.id+'_pager',
                store:store_marcas_lista,
                displayInfo: true,
                displayMsg: '{0} - {1} de {2} Registros',
                emptyMsg: 'No existen registros',
                pageSize:100
            });
			
			pager.on('beforechange',function(bar,params){  
				params.campo = Ext.getCmp(marcas.id+'-combo_describe').getValue();
				params.query = Ext.getCmp(marcas.id+'-buscar').getValue();
			}); 
            
            store_marcas_describe.load({params:{table:'marcas'}});

            var grid_marcas_lista = new Ext.grid.GridPanel({
                id:marcas.id+'-grid_lista',
                store: store_marcas_lista,
                singleSelect:true,
                columnLines:true,
                monitorResize:true,
                width:226,
                height:400,
				bbar:pager,
                loadMask:true,
                sm: new Ext.grid.RowSelectionModel({
                    singleSelect:true
                }),
                columns:
                [
                    {header:'Id',sortable :true,dataIndex:'mar_id',width:25},
                    {header:'Codigo',sortable :true,dataIndex:'codigo',width:100},
					{header:'Nombres',sortable :true,dataIndex:'nombre',width:150},
                    {header:'Activo',sortable :true,dataIndex:'activo',width:150,hidden:true},
                ]
                ,
                listeners:
                {
                    rowdblclick:function()
                    {
                        if(Ext.getCmp(marcas.id+'-btn_editar').isVisible()){
							Ext.getCmp(marcas.id+'-panel_derecho').expand();
				Ext.getCmp(marcas.id+'-panel_derecho').setVisible(true);
                        	marcas.fn_editar();
						}
                    },
					rowclick:function()
                    {
                        Ext.getCmp(marcas.id+'-btn_editar').enable();
						Ext.getCmp(marcas.id+'-btn_eliminar').enable();
                    }
                }
            });

            
            var panel_form=new Ext.Panel({
            layout:'form',
            border:false,
            bodyStyle:'margin:5px;',
            items:
            [
            {
                id:marcas.id+'-formulario',
				xtype:'form',
				frame: true,
                layout:'column',
                border:false,
                items:
                [
                    {
                      xtype:'hidden',
                      id:marcas.id+'-mar_id',
                      value:'0'
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:marcas.id+'-codigo',
                                fieldLabel:'Código',
                                itemCls: 'label01',
                                style:'margin-left:7px',
                                width:80,
                                readOnly:true
                            }
                        ]
                    },
                    {
                        xtype:'panel',labelWidth:120,layout:'form',
                        border:false,columnWidth:1,
                        items:
                        [
                            {
                                xtype:'textfield',
                                id:marcas.id+'-nombre',
                                fieldLabel:'Descripción',
                                itemCls: 'label01',
								style: {textTransform: "uppercase", marginLeft:"7px"},
                                width:350,
								allowBlank:false
                            }
                        ]
                    }
                    
                ]
            }

            ]
            });
            
            var panel = new Ext.Panel({  
            layout: 'border',

                                        tbar:[
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            btn_nuevo,'-',btn_guardar,btn_actualizar,btn_editar,'-',btn_eliminar,btn_cancelar, '-', btn_imprimir,
                            combo_marcas_describe,txt_busqueda
                    
                        ]
                    }],
            bodyStyle:'height:auto;width:70%;margin:auto;',
            border:false,
            items: [
            {  
                region: 'west',
                layout:'fit',
                xtype: 'panel',
                width:'96%',
                autoScroll: true,  
                border:false,
                items:
                [
                    grid_marcas_lista
                    
                ]
            }
            ,
            {
            region:'center',
            width:'0',
            height:'0'
            }
            ,
            {  
                id:marcas.id+'-panel_derecho',
                region: 'east',
                xtype: 'panel',
                collapsible:true,
                layout: 'form',
                split:true,
                collapsed:true,
                width:'100%',
                border:false,
                items:
                [
                    panel_form
                ]  
            }
      ]  
    });
            
            new Ext.Window({
                                        id:'win_marcas',
                                        title:'Marcas', 
                                        width: 800,
                                        height:600,
                                        layout:'fit',
                                        border:false,
                                        frame:true,
                                        autoDestroy:true,
                                        autoScroll:false,
                                        minimizable: false,
                                        maximizable: false,
                                        closable:true,
                                        collapsible:false,
                                        draggable:true,
                                        onEsc:function(){Ext.getCmp('win_marcas').close();}, resizable:true,
                                        items:panel,
                                        buttonAlign:'center'
            });
                Ext.getCmp('win_marcas').show();
                Ext.getCmp('win_marcas').center();
                Ext.getCmp('win_marcas').toFront();
                marcas.fn_habilitar(false,0);
        },
        fn_nuevo:function()
        {            
			Ext.Msg.wait('Generando código de marca... por favor espere!');
			Ext.Ajax.request({
				url:'tablas/marcas-codigo',
				params:
				{
					table:'marcas'
				},
				success:function(response,options)
				{             
					Ext.Msg.hide();
					var res = Ext.decode(response.responseText);
					var numero="00000"+res.AUTO_INCREMENT;
					var codigo="MA"+numero.substr(numero.length-5,5)
					Ext.getCmp(marcas.id+'-codigo').setValue(codigo);
				}
			});
			
            Ext.getCmp(marcas.id+'-mar_id').setValue('');
			Ext.getCmp(marcas.id+'-nombre').setValue('');
                        
            marcas.fn_habilitar(true,1);
        },
        fn_editar:function()
        {
            var rs=Ext.getCmp(marcas.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.getCmp(marcas.id+'-panel_derecho').expand();
				Ext.getCmp(marcas.id+'-panel_derecho').setVisible(true);
				Ext.getCmp(marcas.id+'-codigo').setValue(rs.get('codigo'));
                Ext.getCmp(marcas.id+'-mar_id').setValue(rs.get('mar_id'));
                Ext.getCmp(marcas.id+'-nombre').setValue(rs.get('nombre'));
                
                marcas.fn_habilitar(true,2);
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
        fn_actualizar:function()
        {
            if(marcas.fn_validar()){
				Ext.getCmp(marcas.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/marcas-actualizar',
					params:{ 
						mar_id:Ext.getCmp(marcas.id+'-mar_id').getValue(),
						codigo:Ext.getCmp(marcas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(marcas.id+'-nombre').getValue().toUpperCase(),
					},
					waitTitle: 'Actualizando Informacion',
					waitMsg: 'Enviando datos..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(marcas.id+'-panel_derecho').collapse();
							Ext.getCmp(marcas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							marcas.fn_habilitar(false,0);
							Ext.getCmp(marcas.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(marcas.id+'-combo_describe').getValue(),query:Ext.getCmp(marcas.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(marcas.id+res.campo).focus(true,10);			
						}
						Ext.getCmp(marcas.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(marcas.id+res.campo).focus(true,10);
					}
				});
				/*Ext.Ajax.request({
					url:'tablas/marcas-actualizar',
					params:
					{
						mar_id:Ext.getCmp(marcas.id+'-mar_id').getValue(),
						codigo:Ext.getCmp(marcas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(marcas.id+'-nombre').getValue().toUpperCase(),
					},
					success:function(response,options)
					{             
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(marcas.id+'-panel_derecho').collapse();
							Ext.getCmp(marcas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha actualizado");
							marcas.fn_habilitar(false,0);
							Ext.getCmp(marcas.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(marcas.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
        fn_guardar:function()
        {
            if(marcas.fn_validar()){
				Ext.getCmp(marcas.id+'-formulario').getForm().submit({						
					method: 'POST',
					url:'tablas/marcas-guardar',
					params:{ 
						codigo:Ext.getCmp(marcas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(marcas.id+'-nombre').getValue().toUpperCase(),
					},
					waitTitle: 'Registro de ',
					waitMsg: 'Guardando Información..',
					success: function(form, action){					
						var res = Ext.decode(action.response.responseText);
						if(res.success){
							Ext.getCmp(marcas.id+'-panel_derecho').collapse();
							Ext.getCmp(marcas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							marcas.fn_habilitar(false,0);
							Ext.getCmp(marcas.id+'-grid_lista').store.load({params:{campo:Ext.getCmp(marcas.id+'-combo_describe').getValue(),query:Ext.getCmp(marcas.id+'-buscar').getValue(),start:0,limit:100}});
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(marcas.id+res.campo).focus(true,10);						
						}
						Ext.getCmp(marcas.id+'-formulario').getForm().reset();
					},
					failure: function(form, action){
						var res = Ext.decode(action.response.responseText);
						Ext.Msg.show({
							title:'Error',
							msg: res.mensaje,
							   buttons: Ext.Msg.OK,
							   icon: Ext.MessageBox.ERROR
						});
						Ext.getCmp(marcas.id+res.campo).focus(true,10);							
					}
				});
				/*Ext.Ajax.request({
					url:'tablas/marcas-guardar',
					params:
					{
						codigo:Ext.getCmp(marcas.id+'-codigo').getValue(),
						nombre:Ext.getCmp(marcas.id+'-nombre').getValue().toUpperCase(),
					},
					success:function(response,options)
					{             
						var res = Ext.decode(response.responseText);
						if(res.success){
							Ext.getCmp(marcas.id+'-panel_derecho').collapse();
							Ext.getCmp(marcas.id+'-panel_derecho').setVisible(false);
							og.msg("Ok","El registro se ha guardado");
							marcas.fn_habilitar(false,0);
							Ext.getCmp(marcas.id+'-grid_lista').store.load();
						}else{
							og.msg("Error",res.mensaje);
							Ext.getCmp(marcas.id+res.campo).focus(true,10);							
						}
					}
				});*/
			}
        },
        fn_eliminar:function()
        {
            var rs=Ext.getCmp(marcas.id+'-grid_lista').getSelectionModel().getSelected();
            if(rs)
            {
				Ext.Msg.confirm('Alerta', 'Desea eliminar?<br>Marca :<br>' + rs.get('nombre'), function(btn) {
					if(btn == 'yes')
					{
						Ext.Msg.wait('Eliminando marca... por favor espere!');
						Ext.Ajax.request({
							url:'tablas/marcas-eliminar',
							params:
							{
								mar_id:rs.get('mar_id')
							},
							success:function(response,options)
							{         
								Ext.Msg.hide();    
								var res = Ext.decode(response.responseText);
								if(res.success){
									og.msg("Ok","El registro se ha eliminado");
									marcas.fn_habilitar(false,0);
									Ext.getCmp(marcas.id+'-grid_lista').store.load();
								}else{
									og.msg("Error",res.mensaje);
									Ext.getCmp(marcas.id+res.campo).focus(true,10);							
								}
							}
						});
					}
				 });
            }
            else
            {
                og.msg("Error","Seleccione un registro");
            }
        },
		
		fn_imprimir:function()
        {
			document.getElementById('frmReporte').action="tablas/marcas-lista-impresion";
			document.getElementById('txtpar1').value = Ext.getCmp(marcas.id+'-combo_describe').getValue();
			document.getElementById('txtpar2').value = Ext.getCmp(marcas.id+'-buscar').getValue();
            document.getElementById('frmReporte').submit();
        },
		
		fn_validar:function()
		{
			if(!Ext.getCmp(marcas.id+'-nombre').isValid())
            {
                og.msg("Error", "Ingrese el campo Nombres");
                Ext.getCmp(marcas.id+'-nombre').focus(true,10);
                return false;
            }	
			return true;
		},
		
		fn_habilitar:function(sw, tipo)
        {
			if(!sw){
				Ext.getCmp(marcas.id+'-btn_guardar').setVisible(sw);
				Ext.getCmp(marcas.id+'-btn_actualizar').setVisible(sw);
			}else{
				if(tipo==1){
					Ext.getCmp(marcas.id+'-btn_guardar').setVisible(sw);
					Ext.getCmp(marcas.id+'-btn_actualizar').setVisible(!sw);
				}else{
					Ext.getCmp(marcas.id+'-btn_guardar').setVisible(!sw);
					Ext.getCmp(marcas.id+'-btn_actualizar').setVisible(sw);
				}
			}
			<?php if($this->acceso[1]=='Y'){?>
			Ext.getCmp(marcas.id+'-btn_nuevo').setVisible(!sw);			
			<? } ?>
			Ext.getCmp(marcas.id+'-btn_cancelar').setVisible(sw);
			<?php if($this->acceso[2]=='Y'){?>
			Ext.getCmp(marcas.id+'-btn_editar').setVisible(!sw);
			<? } ?>
			<?php if($this->acceso[3]=='Y'){?>
			Ext.getCmp(marcas.id+'-btn_eliminar').setVisible(!sw);
			<? } ?>

			Ext.getCmp(marcas.id+'-btn_editar').disable();
			Ext.getCmp(marcas.id+'-btn_eliminar').disable();
			
			Ext.getCmp(marcas.id+'-buscar').setVisible(!sw);			
			Ext.getCmp(marcas.id+'-combo_describe').setVisible(!sw);
			
			Ext.getCmp(marcas.id+'-btn_imprimir').setVisible(!sw);			
        }
         
    }
    Ext.onReady(marcas.init,marcas);

</script>